In [41]:
import pandas as pd 

df = pd.read_csv('steam_games_2026.csv')

In [42]:
df.head()
df.info()
print(df.shape)

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   AppID              1000 non-null   int64
 1   Name               1000 non-null   str
 2   Release_Date       999 non-null    str
 3   Primary_Genre      1000 non-null   str
 4   All_Tags           986 non-null    str
 5   Price_USD          1000 non-null   float64
 6   Discount_Pct       1000 non-null   int64
 7   Review_Score_Pct   1000 non-null   int64
 8   Total_Reviews      1000 non-null   int64
 9   Steam_Deck_Status  1000 non-null   str
 10  Estimated_Owners   1000 non-null   int64
 11  24h_Peak_Players   1000 non-null   int64
dtypes: float64(1), int64(6), str(5)
memory usage: 93.9 KB
(1000, 12)

In [43]:
df_val = df['Name'].value_counts
df_des = df['Price_USD'].describe

print(df_val)
print(df_des)

<bound method IndexOpsMixin.value_counts of 0                      Counter-Strike 2
1                      Slay the Spire 2
2                        Crimson Desert
3                              Marathon
4                 Resident Evil Requiem
                     ...
995                         Paleo Pines
996              MARVEL Cosmic Invasion
997    Door Kickers 2: Task Force North
998                        Labyrinthine
999                              Vellum
Name: Name, Length: 1000, dtype: str>
<bound method NDFrame.describe of 0       0.00
1      24.99
2      69.99
3      39.99
4      69.99
       ...
995     7.49
996    29.99
997    24.99
998     9.99
999    11.99
Name: Price_USD, Length: 1000, dtype: float64>

In [44]:
df.loc[2, ['Name', 'Price_USD']]

Name         Crimson Desert
Price_USD             69.99
Name: 2, dtype: object

In [45]:
df.iloc[0:3, 0:5]

,AppID,Name,Release_Date,Primary_Genre,All_Tags
0,730,Counter-Strike 2,2012-08-21,Action,FPS;Shooter;Multiplayer;Competitive;Action;Tea...
1,2868840,Slay the Spire 2,2026-03-05,Indie,Strategy;Roguelike;Card Game;Deckbuilding;Co-o...
2,3321460,Crimson Desert,2026-03-19,Action,Action;Open World;Singleplayer;Adventure;Comba...

In [46]:
df.sort_values(by= 'Name')

,AppID,Name,Release_Date,Primary_Genre,All_Tags,Price_USD,Discount_Pct,Review_Score_Pct,Total_Reviews,Steam_Deck_Status,Estimated_Owners,24h_Peak_Players
787,3768760,007 First Light,2026-05-27,Action,Singleplayer;Action;Adventure;Action-Adventure...,69.99,0,0,0,Unknown,0,0
893,1895900,1348 Ex Voto,2026-03-12,Action,Singleplayer;Third Person;Medieval;Action-Adve...,22.49,10,51,417,Unknown,12510,0
210,251570,7 Days to Die,2024-07-25,Action,Survival;Zombies;Multiplayer;Open World;Open W...,44.99,0,85,270508,Unknown,8115240,17045
851,1629520,A Little to the Left,2022-11-08,Casual,Puzzle;Relaxing;Cute;Casual;Singleplayer;Point...,14.99,0,93,15287,Unknown,458610,422
374,1222700,A Way Out,2020-06-18,Action,Online Co-Op;Co-op;Split Screen;Story Rich;Loc...,2.99,90,88,72109,Unknown,2163270,262
...,...,...,...,...,...,...,...,...,...,...,...,...
525,3226450,iRacing Arcade,2026-03-03,Racing,Racing;Arcade;Driving;Automobile Sim;Managemen...,24.99,0,72,695,Unknown,20850,0
207,2456740,inZOI,2025-03-27,Adventure,Life Sim;Character Customization;Simulation;Re...,39.99,0,74,26794,Unknown,803820,1039
926,590830,s&box,April 2026,Action,Sandbox;Casual;Game Development;Building;Level...,0.00,0,0,0,Unknown,0,0
231,3354750,skate.,2025-09-16,Action,Multiplayer;Skateboarding;Action;Free to Play;...,0.00,0,50,266,Unknown,7980,0
167,518790,theHunter: Call of the Wild™,2017-02-16,Adventure,Hunting;Open World;Multiplayer;Nature;Relaxing...,19.99,0,90,162885,Unknown,4886550,2207

In [ ]:
df = df.drop('All_Tags', axis =1)
df.rename(columns ={'Primary_Genre': 'P_Genre'}, inplace=True)
print(df)

       AppID                              Name Release_Date    P_Genre  \
0        730                  Counter-Strike 2   2012-08-21     Action
1    2868840                  Slay the Spire 2   2026-03-05      Indie
2    3321460                    Crimson Desert   2026-03-19     Action
3    3065800                          Marathon   2026-03-05     Action
4    3764200             Resident Evil Requiem   2026-02-26     Action
..       ...                               ...          ...        ...
995  1202200                       Paleo Pines   2023-09-26  Adventure
996  2753970            MARVEL Cosmic Invasion   2025-12-01     Action
997  1239080  Door Kickers 2: Task Force North   2025-02-10     Action
998  1302240                      Labyrinthine   2023-08-18     Action
999   917950                            Vellum   2025-05-02     Action

     Price_USD  Discount_Pct  Review_Score_Pct  Total_Reviews  \
0         0.00             0                83        4980365
1        24.99             0                97          49549
2        69.99             0                 0              0
3        39.99             0                90          24360
4        69.99             0                96          79667
..         ...           ...               ...            ...
995       7.49            75                93           1921
996      29.99             0                90           1630
997      24.99             0                96          11539
998       9.99             0                70          13549
999      11.99            40                90           1188

    Steam_Deck_Status  Estimated_Owners  24h_Peak_Players
0             Unknown         149410950           1013936
1             Unknown           1486470                 0
2             Unknown                 0                 0
3             Unknown            730800                 0
4             Unknown           2390010                 0
..                ...               ...               ...
995           Unknown             57630                50
996           Unknown             48900                 0
997           Unknown            346170               505
998           Unknown            406470               179
999           Unknown             35640               141

[1000 rows x 11 columns]

In [54]:
df.dtypes

AppID                  int64
Name                     str
Release_Date             str
P_Genre                  str
Price_USD            float64
Discount_Pct           int64
Review_Score_Pct       int64
Total_Reviews          int64
Steam_Deck_Status        str
Estimated_Owners       int64
24h_Peak_Players       int64
dtype: object

In [57]:
df.isna()

,AppID,Name,Release_Date,P_Genre,Price_USD,Discount_Pct,Review_Score_Pct,Total_Reviews,Steam_Deck_Status,Estimated_Owners,24h_Peak_Players
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False

In [58]:
df.isnull()

,AppID,Name,Release_Date,P_Genre,Price_USD,Discount_Pct,Review_Score_Pct,Total_Reviews,Steam_Deck_Status,Estimated_Owners,24h_Peak_Players
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False,False

In [55]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool