In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import seaborn as sns
import os
from datetime import datetime
from pathlib import Path
from apify_client import ApifyClient
from dotenv import load_dotenv

df_05_17 = pd.read_csv(r'D:\Steam_top1000\Data\steam_top_sellers_2026-05-17.csv')
df_06_02 = pd.read_csv(r'D:\Steam_top1000\Data\steam_top_sellers_2026-06-02.csv')
df_07_02 = pd.read_csv(r'D:\Steam_top1000\Data\steam_top_sellers_2026-07-02.csv')


pd.set_option('display.max_rows', None)

In [ ]:
#loading the .env file 
load_dotenv()

#Loads the Apify API token from the `apify_token` environment variable using `os.getenv()`.
apify_token = os.getenv("apify_token")

# Create an Apify client object
# This allows Python to communicate with the Apify platform
client = ApifyClient(apify_token)

# Get today's date and format it as YYYY-MM-DD
# This is used later for timestamped filenames
today = datetime.today().strftime("%Y-%m-%d")

# Define the folder where CSV files will be saved
output_dir = Path(r"D:\Steam_top1000\Data")

# Define the Actor input settings
run_input = {

    # Empty query means no keyword filtering
    "query": "",

    # Steam search URL for the Top Sellers page
    "steamSearchUrls": [
        "https://store.steampowered.com/search/?filter=topsellers"
    ],

    # Maximum number of games to retrieve
    "maxItems": 1000,

    # Use United States Steam store data
    "country": "US",

    # Return results in English
    "language": "english"
}

# Run the Apify Steam scraper Actor
run = client.actor(
    "lokki/steam-top-sellers-scraper"
).call(run_input=run_input)

# Retrieve all scraped dataset items from the completed Actor run
items = list(

    client.dataset(
        run["defaultDatasetId"]
    ).iterate_items()
)

# Convert the returned JSON data into a pandas DataFrame
df = pd.DataFrame(items)

# Print all dataframe column names
print(df.columns)

# Display the first few rows of the dataset
print(df.head())

# Create a timestamped filename
filename = output_dir / f"steam_top_sellers_{today}.csv"

# Export the dataframe to a CSV file

df.to_csv(filename, index=False)

# Print confirmation message showing where the file was saved
print(f"Saved {len(df)} rows to {filename}")

[apify.steam-top-sellers-scraper runId:jfpNGZjy8zNTaylM4] -> Status: RUNNING, Message:
[apify.steam-top-sellers-scraper runId:jfpNGZjy8zNTaylM4] -> 2026-07-28T01:47:57.235Z ACTOR: Pulling container image of build ReAm1K9xi9OZPAt4S from registry.
[apify.steam-top-sellers-scraper runId:jfpNGZjy8zNTaylM4] -> 2026-07-28T01:48:03.418Z ACTOR: Creating container.
[apify.steam-top-sellers-scraper runId:jfpNGZjy8zNTaylM4] -> 2026-07-28T01:48:03.461Z ACTOR: Starting container.
[apify.steam-top-sellers-scraper runId:jfpNGZjy8zNTaylM4] -> 2026-07-28T01:48:03.464Z ACTOR: Running under "LIMITED_PERMISSIONS".
[apify.steam-top-sellers-scraper runId:jfpNGZjy8zNTaylM4] -> 2026-07-28T01:48:04.156Z
[apify.steam-top-sellers-scraper runId:jfpNGZjy8zNTaylM4] -> 2026-07-28T01:48:04.158Z > steam-top-sellers-scraper@1.0.0 start
[apify.steam-top-sellers-scraper runId:jfpNGZjy8zNTaylM4] -> 2026-07-28T01:48:04.160Z > node src/main.js
[apify.steam-top-sellers-scraper runId:jfpNGZjy8zNTaylM4] -> 2026-07-28T01:48:04.162Z
[apify.steam-top-sellers-scraper runId:jfpNGZjy8zNTaylM4] -> 2026-07-28T01:48:04.678Z INFO  System info {"apifyVersion":"3.7.1","apifyClientVersion":"2.23.1","crawleeVersion":"3.16.0","osType":"Linux","nodeVersion":"v20.20.2"}

I had found an api online that would provide me all of current information for the top 1000 steam games. The API I am using is Steam Market Intelligence: Top Sellers & Opportunity Tracker, from "lokki/steam-top-sellers-scraper". I had planned on going back through and changing column names and making sure the data sets where structured similarly, however with the api call making a new csv each time it is ran with a time stamp, I may choose to do away with the original csv to provide the most up-to-date modle. For my capstone I will be generating a few more snapshots of data and ploting that data to show the changes over time within the estimated ownership of multiplayer vs singleplayer games. Though I am still not sure all this API can do, if it cannot get past data snapshots I may find another api that can so I can show a more acurate reprsentation of the data, as I would only have data within this month or so.

In [3]:
df_05_17.head()

,rank,appId,title,url,releaseDate,priceText,finalPriceCents,discountPercent,reviewSummary,reviewPercent,...,marketPosition,opportunityType,pricingPosition,audienceSignal,monetizationSignal,competitiveSignal,intelligenceTags,riskFlags,insightSummary,recommendedAction
0,1,1962700,Subnautica 2,https://store.steampowered.com/app/1962700/Sub...,"May 14, 2026",$29.99,2999,0.0,Very Positive,94.0,...,Breakout leader,Benchmark competitor,Mid-market,Community / multiplayer audience,Paid upfront,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Subnautica 2 is a breakout leader, opportunity...","Use as a benchmark for capsule, pricing, tags,..."
1,2,2483190,Forza Horizon 6,https://store.steampowered.com/app/2483190/For...,"May 18, 2026",$69.99,6999,0.0,Very Positive,86.0,...,Standard competitor,Baseline market data,High-ticket,Community / multiplayer audience,Paid upfront,Comparable baseline,"['loved-by-players', 'social-retention-loop', ...",[],"Forza Horizon 6 is a standard competitor, oppo...",Use as baseline competitor data; enrich with r...
2,3,730,Counter-Strike 2,https://store.steampowered.com/app/730/Counter...,"Aug 21, 2012",Free,1499,NaN,Very Positive,86.0,...,Breakout leader,Benchmark competitor,Free-to-play,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Counter-Strike 2 is a breakout leader, opportu...","Use as a benchmark for capsule, pricing, tags,..."
3,4,2767030,Marvel Rivals,https://store.steampowered.com/app/2767030/Mar...,"Dec 5, 2024",Free,0,NaN,Mostly Positive,77.0,...,Breakout leader,Benchmark competitor,Free-to-play,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Marvel Rivals is a breakout leader, opportunit...","Use as a benchmark for capsule, pricing, tags,..."
4,5,2215200,LEGO® Batman™: Legacy of the Dark Knight,https://store.steampowered.com/app/2215200/LEG...,"May 22, 2026",$69.99,6999,0.0,NaN,NaN,...,Early momentum signal,Watchlist candidate,High-ticket,Community / multiplayer audience,Paid upfront,Comparable baseline,"['social-retention-loop', 'fresh-release']",['review-data-missing-or-not-yet-established'],LEGO® Batman™: Legacy of the Dark Knight is a ...,Monitor daily; early movement can reveal emerg...

In [4]:
df_05_17.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   rank                  1000 non-null   int64
 1   appId                 1000 non-null   int64
 2   title                 1000 non-null   str
 3   url                   1000 non-null   str
 4   releaseDate           1000 non-null   str
 5   priceText             999 non-null    str
 6   finalPriceCents       1000 non-null   int64
 7   discountPercent       900 non-null    float64
 8   reviewSummary         979 non-null    str
 9   reviewPercent         979 non-null    float64
 10  reviewCount           979 non-null    float64
 11  platforms             1000 non-null   str
 12  imageUrl              1000 non-null   str
 13  scrapedAt             1000 non-null   str
 14  currentPlayers        990 non-null    float64
 15  developer             501 non-null    str
 16  publisher             499 non-null    str
 17  genres                1000 non-null   str
 18  categories            1000 non-null   str
 19  recommendationsTotal  454 non-null    float64
 20  metacriticScore       130 non-null    float64
 21  shortDescription      503 non-null    str
 22  isFree                503 non-null    object
 23  type                  503 non-null    str
 24  demandScore           1000 non-null   int64
 25  qualityScore          1000 non-null   int64
 26  commercialScore       1000 non-null   int64
 27  momentumScore         1000 non-null   int64
 28  opportunityScore      1000 non-null   int64
 29  marketPosition        1000 non-null   str
 30  opportunityType       1000 non-null   str
 31  pricingPosition       1000 non-null   str
 32  audienceSignal        1000 non-null   str
 33  monetizationSignal    1000 non-null   str
 34  competitiveSignal     1000 non-null   str
 35  intelligenceTags      1000 non-null   str
 36  riskFlags             1000 non-null   str
 37  insightSummary        1000 non-null   str
 38  recommendedAction     1000 non-null   str
dtypes: float64(6), int64(8), object(1), str(24)
memory usage: 304.8+ KB

In [5]:
df_05_17.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [6]:
df_05_17.isnull().sum()

rank                      0
appId                     0
title                     0
url                       0
releaseDate               0
priceText                 1
finalPriceCents           0
discountPercent         100
reviewSummary            21
reviewPercent            21
reviewCount              21
platforms                 0
imageUrl                  0
scrapedAt                 0
currentPlayers           10
developer               499
publisher               501
genres                    0
categories                0
recommendationsTotal    546
metacriticScore         870
shortDescription        497
isFree                  497
type                    497
demandScore               0
qualityScore              0
commercialScore           0
momentumScore             0
opportunityScore          0
marketPosition            0
opportunityType           0
pricingPosition           0
audienceSignal            0
monetizationSignal        0
competitiveSignal         0
intelligenceTags          0
riskFlags                 0
insightSummary            0
recommendedAction         0
dtype: int64

In [7]:
df_06_02.head()

,rank,appId,title,url,releaseDate,priceText,finalPriceCents,discountPercent,reviewSummary,reviewPercent,...,marketPosition,opportunityType,pricingPosition,audienceSignal,monetizationSignal,competitiveSignal,intelligenceTags,riskFlags,insightSummary,recommendedAction
0,1,730,Counter-Strike 2,https://store.steampowered.com/app/730/Counter...,"Aug 21, 2012",Free,1499,NaN,Very Positive,86.0,...,Breakout leader,Benchmark competitor,Free-to-play,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Counter-Strike 2 is a breakout leader, opportu...","Use as a benchmark for capsule, pricing, tags,..."
1,2,2483190,Forza Horizon 6,https://store.steampowered.com/app/2483190/For...,"May 18, 2026",$69.99,6999,0.0,Very Positive,86.0,...,Breakout leader,Benchmark competitor,High-ticket,Community / multiplayer audience,Paid upfront,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Forza Horizon 6 is a breakout leader, opportun...","Use as a benchmark for capsule, pricing, tags,..."
2,3,359550,Tom Clancy's Rainbow Six Siege,https://store.steampowered.com/app/359550/Tom_...,"Dec 1, 2015",Free,999,NaN,Very Positive,82.0,...,Breakout leader,Benchmark competitor,Free-to-play,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],Tom Clancy's Rainbow Six Siege is a breakout l...,"Use as a benchmark for capsule, pricing, tags,..."
3,4,1675200,Steam Deck,https://store.steampowered.com/app/1675200/Ste...,"Jan 17, 2025",$789.00,39900,0.0,NaN,NaN,...,Non-game / accessory listing,Catalog monitoring,High-ticket,General Steam audience,Paid upfront,Comparable baseline,['non-game-hardware'],"['review-data-missing-or-not-yet-established',...","Steam Deck is a non-game / accessory listing, ...","Keep for catalog awareness, but exclude from g..."
4,5,2694490,Path of Exile 2,https://store.steampowered.com/app/2694490/Pat...,"Dec 6, 2024",$14.99,1499,50.0,Mostly Positive,76.0,...,Breakout leader,Benchmark competitor,Promotional discount,Community / multiplayer audience,Discount-driven sales,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Path of Exile 2 is a breakout leader, opportun...","Use as a benchmark for capsule, pricing, tags,..."

In [8]:
df_06_02.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   rank                  1000 non-null   int64
 1   appId                 1000 non-null   int64
 2   title                 1000 non-null   str
 3   url                   1000 non-null   str
 4   releaseDate           999 non-null    str
 5   priceText             998 non-null    str
 6   finalPriceCents       1000 non-null   int64
 7   discountPercent       885 non-null    float64
 8   reviewSummary         969 non-null    str
 9   reviewPercent         969 non-null    float64
 10  reviewCount           969 non-null    float64
 11  platforms             1000 non-null   str
 12  imageUrl              1000 non-null   str
 13  scrapedAt             1000 non-null   str
 14  currentPlayers        983 non-null    float64
 15  developer             397 non-null    str
 16  publisher             394 non-null    str
 17  genres                1000 non-null   str
 18  categories            1000 non-null   str
 19  recommendationsTotal  341 non-null    float64
 20  metacriticScore       118 non-null    float64
 21  shortDescription      399 non-null    str
 22  isFree                400 non-null    object
 23  type                  400 non-null    str
 24  demandScore           1000 non-null   int64
 25  qualityScore          1000 non-null   int64
 26  commercialScore       1000 non-null   int64
 27  momentumScore         1000 non-null   int64
 28  opportunityScore      1000 non-null   int64
 29  marketPosition        1000 non-null   str
 30  opportunityType       1000 non-null   str
 31  pricingPosition       1000 non-null   str
 32  audienceSignal        1000 non-null   str
 33  monetizationSignal    1000 non-null   str
 34  competitiveSignal     1000 non-null   str
 35  intelligenceTags      1000 non-null   str
 36  riskFlags             1000 non-null   str
 37  insightSummary        1000 non-null   str
 38  recommendedAction     1000 non-null   str
dtypes: float64(6), int64(8), object(1), str(24)
memory usage: 304.8+ KB

In [9]:
df_06_02.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [10]:
df_06_02.isnull().sum()

rank                      0
appId                     0
title                     0
url                       0
releaseDate               1
priceText                 2
finalPriceCents           0
discountPercent         115
reviewSummary            31
reviewPercent            31
reviewCount              31
platforms                 0
imageUrl                  0
scrapedAt                 0
currentPlayers           17
developer               603
publisher               606
genres                    0
categories                0
recommendationsTotal    659
metacriticScore         882
shortDescription        601
isFree                  600
type                    600
demandScore               0
qualityScore              0
commercialScore           0
momentumScore             0
opportunityScore          0
marketPosition            0
opportunityType           0
pricingPosition           0
audienceSignal            0
monetizationSignal        0
competitiveSignal         0
intelligenceTags          0
riskFlags                 0
insightSummary            0
recommendedAction         0
dtype: int64

In [11]:
df_07_02.head()

,rank,appId,title,url,releaseDate,priceText,finalPriceCents,discountPercent,reviewSummary,reviewPercent,...,marketPosition,opportunityType,pricingPosition,audienceSignal,monetizationSignal,competitiveSignal,intelligenceTags,riskFlags,insightSummary,recommendedAction
0,1,4165910,Steam Machine,https://store.steampowered.com/app/4165910/Ste...,"Jun 22, 2026","$1,049.00",104900,0.0,NaN,NaN,...,Non-game / accessory listing,Catalog monitoring,High-ticket,General Steam audience,Paid upfront,Comparablea baseline,"['fresh-release', 'non-game-hardware']","['review-data-missing-or-not-yet-established',...",Steam Machine is aa non-game / accessory listi...,"Keep for catalog awareness, but exclude from g..."
1,2,2767030,Marvel Rivals,https://store.steampowered.com/app/2767030/Mar...,"Dec 5, 2024",Free,0,NaN,Mostly Positive,77.0,...,Commercially aggressive,Pricing/monetization benchmark,Free-to-play,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['high-demand', 'loved-by-players', 'free-to-p...",[],"Marvel Rivals is a commercially aggressive, op...","Compare discount depth, price tier, and moneti..."
2,3,730,Counter-Strike 2,https://store.steampowered.com/app/730/Counter...,"Aug 21, 2012",Free,1499,NaN,Very Positive,86.0,...,Breakout leader,Benchmark competitor,Free-to-play,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Counter-Strike 2 is a breakout leader, opportu...","Use as a benchmark for capsule, pricing, tags,..."
3,4,4704690,MECCHA CHAMELEON,https://store.steampowered.com/app/4704690/MEC...,"Jun 9, 2026",$5.99,599,0.0,Very Positive,89.0,...,Breakout leader,Benchmark competitor,Budget,Community / multiplayer audience,Paid upfront,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"MECCHA CHAMELEON is a breakout leader, opportu...","Use as a benchmark for capsule, pricing, tags,..."
4,5,252490,Rust,https://store.steampowered.com/app/252490/Rust/,"Feb 8, 2018",$19.99,1999,50.0,Very Positive,86.0,...,Breakout leader,Benchmark competitor,Promotional discount,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Rust is a breakout leader, opportunity score 9...","Use as a benchmark for capsule, pricing, tags,..."

In [12]:
df_07_02.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   rank                  1000 non-null   int64
 1   appId                 1000 non-null   int64
 2   title                 1000 non-null   str
 3   url                   1000 non-null   str
 4   releaseDate           1000 non-null   str
 5   priceText             997 non-null    str
 6   finalPriceCents       1000 non-null   int64
 7   discountPercent       905 non-null    float64
 8   reviewSummary         965 non-null    str
 9   reviewPercent         965 non-null    float64
 10  reviewCount           965 non-null    float64
 11  platforms             1000 non-null   str
 12  imageUrl              1000 non-null   str
 13  scrapedAt             1000 non-null   str
 14  currentPlayers        979 non-null    float64
 15  developer             530 non-null    str
 16  publisher             526 non-null    str
 17  genres                1000 non-null   str
 18  categories            1000 non-null   str
 19  recommendationsTotal  477 non-null    float64
 20  metacriticScore       173 non-null    float64
 21  shortDescription      532 non-null    str
 22  isFree                532 non-null    object
 23  type                  532 non-null    str
 24  demandScore           1000 non-null   int64
 25  qualityScore          1000 non-null   int64
 26  commercialScore       1000 non-null   int64
 27  momentumScore         1000 non-null   int64
 28  opportunityScore      1000 non-null   int64
 29  marketPosition        1000 non-null   str
 30  opportunityType       1000 non-null   str
 31  pricingPosition       1000 non-null   str
 32  audienceSignal        1000 non-null   str
 33  monetizationSignal    1000 non-null   str
 34  competitiveSignal     1000 non-null   str
 35  intelligenceTags      1000 non-null   str
 36  riskFlags             1000 non-null   str
 37  insightSummary        1000 non-null   str
 38  recommendedAction     1000 non-null   str
dtypes: float64(6), int64(8), object(1), str(24)
memory usage: 304.8+ KB

In [13]:
df_07_02.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [14]:
df_07_02.isnull().sum()

rank                      0
appId                     0
title                     0
url                       0
releaseDate               0
priceText                 3
finalPriceCents           0
discountPercent          95
reviewSummary            35
reviewPercent            35
reviewCount              35
platforms                 0
imageUrl                  0
scrapedAt                 0
currentPlayers           21
developer               470
publisher               474
genres                    0
categories                0
recommendationsTotal    523
metacriticScore         827
shortDescription        468
isFree                  468
type                    468
demandScore               0
qualityScore              0
commercialScore           0
momentumScore             0
opportunityScore          0
marketPosition            0
opportunityType           0
pricingPosition           0
audienceSignal            0
monetizationSignal        0
competitiveSignal         0
intelligenceTags          0
riskFlags                 0
insightSummary            0
recommendedAction         0
dtype: int64

In [2]:
# Combine the three dataframes into one, ignoring the original index to create a new continuous index allowing me to create a developer and publisher lookup table in preparation for the database.
dfs_combined = pd.concat([df_05_17, df_06_02, df_07_02], ignore_index=True)

dev_lookup = (dfs_combined[['developer']].drop_duplicates().reset_index(drop=True))
dev_lookup['developerID'] = dev_lookup.index + 1

publisher_lookup = (dfs_combined[['publisher']].drop_duplicates().reset_index(drop=True))
publisher_lookup['publisherID'] = publisher_lookup.index + 1

In [ ]:
# Created a variable to hold the three dataframes for May, June, and July
df_05_to_07 = [df_05_17, df_06_02, df_07_02, dfs_combined]

#Created a for loop to iterate through the list of dataframes and perform the following operations on each dataframe:
for df in df_05_to_07:
    df.drop(columns=['recommendationsTotal', 'metacriticScore', 'shortDescription', 'isFree', 'recommendedAction'], inplace=True)

    #Droping the Steam Machine and Steam Deck from the dataset as they are not games 
    df.drop(df[df['title'] == 'Steam Machine'].index, inplace=True)
    df.drop(df[df['title'] == 'Steam Deck'].index, inplace=True)
    df.drop(df[df['type'] != 'game'].index, inplace=True)

    #Updating the missing publisher manually due to it being the only one missing 
    #Puiblisher was originally Nuverse (2022–2025) but the current publisher for the game is Skystone Games as of 2025 
        #-- [Marvel Snap - Wikipedia](https://en.wikipedia.org/wiki/Marvel_Snap)
    df.loc[df['appID'] == 	1997040, 'publisher'] = 'Skystone Games'

    # Reset the DataFrame index
    df.reset_index(drop=True, inplace=True)

    # Renumbered the rank column to follow the ranking of just the games
    df['rank'] = range(1, len(df) + 1)

    #The dataframes are being renamed to have a 'tags' column instead of 'categories' as the content of that column are labled as 'tags' in the Steam store
    df.rename(columns={'categories': 'tags'}, inplace=True)

    # Mapped developer and publisher names to their respective IDs
    df['developerID'] = df['developer'].map(dev_lookup.set_index('developer')['developerID'])
    df['publisherID'] = df['publisher'].map(publisher_lookup.set_index('publisher')['publisherID'])

In [4]:
dfs_combined['type'].value_counts()

type
game    1287
Name: count, dtype: int64

In [5]:
df_07_02.head()

,rank,appId,title,url,releaseDate,priceText,finalPriceCents,discountPercent,reviewSummary,reviewPercent,...,opportunityType,pricingPosition,audienceSignal,monetizationSignal,competitiveSignal,intelligenceTags,riskFlags,insightSummary,developerID,publisherID
0,1,2767030,Marvel Rivals,https://store.steampowered.com/app/2767030/Mar...,"Dec 5, 2024",Free,0,NaN,Mostly Positive,77.0,...,Pricing/monetization benchmark,Free-to-play,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['high-demand', 'loved-by-players', 'free-to-p...",[],"Marvel Rivals is a commercially aggressive, op...",4,4
1,2,730,Counter-Strike 2,https://store.steampowered.com/app/730/Counter...,"Aug 21, 2012",Free,1499,NaN,Very Positive,86.0,...,Benchmark competitor,Free-to-play,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Counter-Strike 2 is a breakout leader, opportu...",3,3
2,3,4704690,MECCHA CHAMELEON,https://store.steampowered.com/app/4704690/MEC...,"Jun 9, 2026",$5.99,599,0.0,Very Positive,89.0,...,Benchmark competitor,Budget,Community / multiplayer audience,Paid upfront,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"MECCHA CHAMELEON is a breakout leader, opportu...",530,394
3,4,252490,Rust,https://store.steampowered.com/app/252490/Rust/,"Feb 8, 2018",$19.99,1999,50.0,Very Positive,86.0,...,Benchmark competitor,Promotional discount,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Rust is a breakout leader, opportunity score 9...",26,24
4,5,381210,Dead by Daylight,https://store.steampowered.com/app/381210/Dead...,"Jun 14, 2016",$7.99,799,60.0,Mostly Positive,79.0,...,Benchmark competitor,Promotional discount,Community / multiplayer audience,Discount-driven sales,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Dead by Daylight is a breakout leader, opportu...",24,23

In [6]:
df_07_02.dtypes

rank                    int64
appId                   int64
title                     str
url                       str
releaseDate               str
priceText                 str
finalPriceCents         int64
discountPercent       float64
reviewSummary             str
reviewPercent         float64
reviewCount           float64
platforms                 str
imageUrl                  str
scrapedAt                 str
currentPlayers        float64
developer                 str
publisher                 str
genres                    str
tags                      str
type                      str
demandScore             int64
qualityScore            int64
commercialScore         int64
momentumScore           int64
opportunityScore        int64
marketPosition            str
opportunityType           str
pricingPosition           str
audienceSignal            str
monetizationSignal        str
competitiveSignal         str
intelligenceTags          str
riskFlags                 str
insightSummary            str
developerID             int64
publisherID             int64
dtype: object

In [7]:
dfs_combined.isnull().sum()

rank                    0
appId                   0
title                   0
url                     0
releaseDate             0
priceText               1
finalPriceCents         0
discountPercent       174
reviewSummary          32
reviewPercent          32
reviewCount            32
platforms               0
imageUrl                0
scrapedAt               0
currentPlayers         32
developer               0
publisher               1
genres                  0
tags                    0
type                    0
demandScore             0
qualityScore            0
commercialScore         0
momentumScore           0
opportunityScore        0
marketPosition          0
opportunityType         0
pricingPosition         0
audienceSignal          0
monetizationSignal      0
competitiveSignal       0
intelligenceTags        0
riskFlags               0
insightSummary          0
developerID             0
publisherID             0
dtype: int64

In [8]:
dfs_combined.count()

rank                  1287
appId                 1287
title                 1287
url                   1287
releaseDate           1287
priceText             1286
finalPriceCents       1287
discountPercent       1113
reviewSummary         1255
reviewPercent         1255
reviewCount           1255
platforms             1287
imageUrl              1287
scrapedAt             1287
currentPlayers        1255
developer             1287
publisher             1286
genres                1287
tags                  1287
type                  1287
demandScore           1287
qualityScore          1287
commercialScore       1287
momentumScore         1287
opportunityScore      1287
marketPosition        1287
opportunityType       1287
pricingPosition       1287
audienceSignal        1287
monetizationSignal    1287
competitiveSignal     1287
intelligenceTags      1287
riskFlags             1287
insightSummary        1287
developerID           1287
publisherID           1287
dtype: int64

In [18]:
#Checking for all games missing developer or publisher information in the combined dataframe
dfs_combined.loc[dfs_combined['developer'].isnull() | dfs_combined['publisher'].isnull(), 'title']

1127    MARVEL SNAP
Name: title, dtype: str

In [26]:
dfs_combined[dfs_combined['title'].str.contains('Marvel Snap', case=False, na=False)][['appId', 'title']]

        appId        title
1127  1997040  MARVEL SNAP

In [29]:
dfs_combined.loc[dfs_combined['reviewSummary'].isnull() | dfs_combined['reviewPercent'].isnull() | dfs_combined['reviewCount'].isnull() | dfs_combined['currentPlayers'].isnull(), 'title']

1                                Forza Horizon 6
4       LEGO® Batman™: Legacy of the Dark Knight
15                       Hell Let Loose: Vietnam
50                               007 First Light
134         Assassin's Creed Black Flag Resynced
172                                      EA Play
338                              Gothic 1 Remake
420                   STAR WARS: Galactic Racer™
437            Avatar Legends: The Fighting Game
455                 ACE COMBAT 8: WINGS OF THEVE
477                             CONTROL Resonant
504                      Hell Let Loose: Vietnam
513                              Gothic 1 Remake
525                        Rayman Legends Retold
526              Tomb Raider: Legacy of Atlantis
544                   Onimusha: Way of the Sword
557         Assassin's Creed Black Flag Resynced
587             Warhammer 40,000: Dawn of War IV
593                 MARVEL Tōkon: Fighting Souls
602                        SILENT HILL: Townfall
605                                 Planet Zoo 2
622                            Echoes of Aincrad
820            Avatar Legends: The Fighting Game
821         Assassin's Creed Black Flag Resynced
828               EA SPORTS™ College Football 27
831                            Echoes of Aincrad
889                     EA SPORTS™ Madden NFL 27
895                       Halo: Campaign Evolved
965                 MARVEL Tōkon: Fighting Souls
1054            Warhammer 40,000: Dawn of War IV
1105            Call of Duty®: Modern Warfare® 4
1155                            CONTROL Resonant
1250                Castlevania: Belmont's Curse
Name: title, dtype: str

In [31]:
dfs_combined.loc[dfs_combined['reviewSummary'].isnull() | dfs_combined['reviewPercent'].isnull() | dfs_combined['reviewCount'].isnull() | dfs_combined['currentPlayers'].isnull(), 'title'].count()

np.int64(33)

I noticed that reviewSummary, reviewPercent, reviewCount,  and currentPlayers all had 32 nulls, I assumed all might be the same 32 games. 
When I checked the count of the games returned I noticed it said 33 not the expected 32.

np.int64(1287)