In [1449]:
import pandas as pd 
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import seaborn as sns
import ast



df_05_17 = pd.read_csv(r'D:\Steam_top1000\Data\steam_top_sellers_2026-05-17.csv')
df_06_02 = pd.read_csv(r'D:\Steam_top1000\Data\steam_top_sellers_2026-06-02.csv')
df_07_02 = pd.read_csv(r'D:\Steam_top1000\Data\steam_top_sellers_2026-07-02.csv')


pd.set_option('display.max_rows', None)

I had found an api online that would provide me all of current information for the top 1000 steam games. The API I am using is Steam Market Intelligence: Top Sellers & Opportunity Tracker, from "lokki/steam-top-sellers-scraper". I had planned on going back through and changing column names and making sure the data sets where structured similarly, however with the api call making a new csv each time it is ran with a time stamp, I may choose to do away with the original csv to provide the most up-to-date modle. For my capstone I will be generating a few more snapshots of data and ploting that data to show the changes over time within the estimated ownership of multiplayer vs singleplayer games. Though I am still not sure all this API can do, if it cannot get past data snapshots I may find another api that can so I can show a more acurate reprsentation of the data, as I would only have data within this month or so.

In [1450]:
df_05_17.head()

,rank,appId,title,url,releaseDate,priceText,finalPriceCents,discountPercent,reviewSummary,reviewPercent,...,marketPosition,opportunityType,pricingPosition,audienceSignal,monetizationSignal,competitiveSignal,intelligenceTags,riskFlags,insightSummary,recommendedAction
0,1,1962700,Subnautica 2,https://store.steampowered.com/app/1962700/Sub...,"May 14, 2026",$29.99,2999,0.0,Very Positive,94.0,...,Breakout leader,Benchmark competitor,Mid-market,Community / multiplayer audience,Paid upfront,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Subnautica 2 is a breakout leader, opportunity...","Use as a benchmark for capsule, pricing, tags,..."
1,2,2483190,Forza Horizon 6,https://store.steampowered.com/app/2483190/For...,"May 18, 2026",$69.99,6999,0.0,Very Positive,86.0,...,Standard competitor,Baseline market data,High-ticket,Community / multiplayer audience,Paid upfront,Comparable baseline,"['loved-by-players', 'social-retention-loop', ...",[],"Forza Horizon 6 is a standard competitor, oppo...",Use as baseline competitor data; enrich with r...
2,3,730,Counter-Strike 2,https://store.steampowered.com/app/730/Counter...,"Aug 21, 2012",Free,1499,NaN,Very Positive,86.0,...,Breakout leader,Benchmark competitor,Free-to-play,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Counter-Strike 2 is a breakout leader, opportu...","Use as a benchmark for capsule, pricing, tags,..."
3,4,2767030,Marvel Rivals,https://store.steampowered.com/app/2767030/Mar...,"Dec 5, 2024",Free,0,NaN,Mostly Positive,77.0,...,Breakout leader,Benchmark competitor,Free-to-play,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Marvel Rivals is a breakout leader, opportunit...","Use as a benchmark for capsule, pricing, tags,..."
4,5,2215200,LEGO® Batman™: Legacy of the Dark Knight,https://store.steampowered.com/app/2215200/LEG...,"May 22, 2026",$69.99,6999,0.0,NaN,NaN,...,Early momentum signal,Watchlist candidate,High-ticket,Community / multiplayer audience,Paid upfront,Comparable baseline,"['social-retention-loop', 'fresh-release']",['review-data-missing-or-not-yet-established'],LEGO® Batman™: Legacy of the Dark Knight is a ...,Monitor daily; early movement can reveal emerg...

In [1451]:
df_05_17.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   rank                  1000 non-null   int64
 1   appId                 1000 non-null   int64
 2   title                 1000 non-null   str
 3   url                   1000 non-null   str
 4   releaseDate           1000 non-null   str
 5   priceText             999 non-null    str
 6   finalPriceCents       1000 non-null   int64
 7   discountPercent       900 non-null    float64
 8   reviewSummary         979 non-null    str
 9   reviewPercent         979 non-null    float64
 10  reviewCount           979 non-null    float64
 11  platforms             1000 non-null   str
 12  imageUrl              1000 non-null   str
 13  scrapedAt             1000 non-null   str
 14  currentPlayers        990 non-null    float64
 15  developer             501 non-null    str
 16  publisher             499 non-null    str
 17  genres                1000 non-null   str
 18  categories            1000 non-null   str
 19  recommendationsTotal  454 non-null    float64
 20  metacriticScore       130 non-null    float64
 21  shortDescription      503 non-null    str
 22  isFree                503 non-null    object
 23  type                  503 non-null    str
 24  demandScore           1000 non-null   int64
 25  qualityScore          1000 non-null   int64
 26  commercialScore       1000 non-null   int64
 27  momentumScore         1000 non-null   int64
 28  opportunityScore      1000 non-null   int64
 29  marketPosition        1000 non-null   str
 30  opportunityType       1000 non-null   str
 31  pricingPosition       1000 non-null   str
 32  audienceSignal        1000 non-null   str
 33  monetizationSignal    1000 non-null   str
 34  competitiveSignal     1000 non-null   str
 35  intelligenceTags      1000 non-null   str
 36  riskFlags             1000 non-null   str
 37  insightSummary        1000 non-null   str
 38  recommendedAction     1000 non-null   str
dtypes: float64(6), int64(8), object(1), str(24)
memory usage: 304.8+ KB

In [1452]:
df_05_17.duplicated()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154    False
155    False
156    False
157    False
158    False
159    False
160    False
161    False
162    False
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172    False
173    False
174    False
175    False
176    False
177    False
178    False
179    False
180    False
181    False
182    False
183    False
184    False
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
205    False
206    False
207    False
208    False
209    False
210    False
211    False
212    False
213    False
214    False
215    False
216    False
217    False
218    False
219    False
220    False
221    False
222    False
223    False
224    False
225    False
226    False
227    False
228    False
229    False
230    False
231    False
232    False
233    False
234    False
235    False
236    False
237    False
238    False
239    False
240    False
241    False
242    False
243    False
244    False
245    False
246    False
247    False
248    False
249    False
250    False
251    False
252    False
253    False
254    False
255    False
256    False
257    False
258    False
259    False
260    False
261    False
262    False
263    False
264    False
265    False
266    False
267    False
268    False
269    False
270    False
271    False
272    False
273    False
274    False
275    False
276    False
277    False
278    False
279    False
280    False
281    False
282    False
283    False
284    False
285    False
286    False
287    False
288    False
289    False
290    False
291    False
292    False
293    False
294    False
295    False
296    False
297    False
298    False
299    False
300    False
301    False
302    False
303    False
304    False
305    False
306    False
307    False
308    False
309    False
310    False
311    False
312    False
313    False
314    False
315    False
316    False
317    False
318    False
319    False
320    False
321    False
322    False
323    False
324    False
325    False
326    False
327    False
328    False
329    False
330    False
331    False
332    False
333    False
334    False
335    False
336    False
337    False
338    False
339    False
340    False
341    False
342    False
343    False
344    False
345    False
346    False
347    False
348    False
349    False
350    False
351    False
352    False
353    False
354    False
355    False
356    False
357    False
358    False
359    False
360    False
361    False
362    False
363    False
364    False
365    False
366    False
367    False
368    False
369    False
370    False
371    False
372    False
373    False
374    False
375    False
376    False
377    False
378    False
379    False
380    False
381    False
382    False
383    False
384    False
385    False
386    False
387    False
388    False
389    False
390    False
391    False
392    False
393    False
394    False
395    False
396    False
397    False
398    False
399    False
400    False
401    False
402    False
403    False
404    False
405    False
406    False
407    False
408    False
409    False
410    False
411    False
412    False
413    False
414    False
415    False
416    False
417    False
418    False
419    False
420    False
421    False
422    False
423    False
424    False
425    False
426    False
427    False
428    False
429    False
430    False
431    False
432    False
433    False
434    False
435    False
436    False
437    False
438    False
439    False
440    False
441    False
442    False
443    False
444    False
445    False
446    False
447    False
448    False
449    False
450    False
451    False
452    False
453    False
454    False
455    False
456    False
457    False
458    False
459    False
460    False
461    False
462    False
463    False
464    False
465    False
466    False
467    False
468    False
469    False
470    False
471    False
472    False
473    False
474    False
475    False
476    False
477    False
478    False
479    False
480    False
481    False
482    False
483    False
484    False
485    False
486    False
487    False
488    False
489    False
490    False
491    False
492    False
493    False
494    False
495    False
496    False
497    False
498    False
499    False
500    False
501    False
502    False
503    False
504    False
505    False
506    False
507    False
508    False
509    False
510    False
511    False
512    False
513    False
514    False
515    False
516    False
517    False
518    False
519    False
520    False
521    False
522    False
523    False
524    False
525    False
526    False
527    False
528    False
529    False
530    False
531    False
532    False
533    False
534    False
535    False
536    False
537    False
538    False
539    False
540    False
541    False
542    False
543    False
544    False
545    False
546    False
547    False
548    False
549    False
550    False
551    False
552    False
553    False
554    False
555    False
556    False
557    False
558    False
559    False
560    False
561    False
562    False
563    False
564    False
565    False
566    False
567    False
568    False
569    False
570    False
571    False
572    False
573    False
574    False
575    False
576    False
577    False
578    False
579    False
580    False
581    False
582    False
583    False
584    False
585    False
586    False
587    False
588    False
589    False
590    False
591    False
592    False
593    False
594    False
595    False
596    False
597    False
598    False
599    False
600    False
601    False
602    False
603    False
604    False
605    False
606    False
607    False
608    False
609    False
610    False
611    False
612    False
613    False
614    False
615    False
616    False
617    False
618    False
619    False
620    False
621    False
622    False
623    False
624    False
625    False
626    False
627    False
628    False
629    False
630    False
631    False
632    False
633    False
634    False
635    False
636    False
637    False
638    False
639    False
640    False
641    False
642    False
643    False
644    False
645    False
646    False
647    False
648    False
649    False
650    False
651    False
652    False
653    False
654    False
655    False
656    False
657    False
658    False
659    False
660    False
661    False
662    False
663    False
664    False
665    False
666    False
667    False
668    False
669    False
670    False
671    False
672    False
673    False
674    False
675    False
676    False
677    False
678    False
679    False
680    False
681    False
682    False
683    False
684    False
685    False
686    False
687    False
688    False
689    False
690    False
691    False
692    False
693    False
694    False
695    False
696    False
697    False
698    False
699    False
700    False
701    False
702    False
703    False
704    False
705    False
706    False
707    False
708    False
709    False
710    False
711    False
712    False
713    False
714    False
715    False
716    False
717    False
718    False
719    False
720    False
721    False
722    False
723    False
724    False
725    False
726    False
727    False
728    False
729    False
730    False
731    False
732    False
733    False
734    False
735    False
736    False
737    False
738    False
739    False
740    False
741    False
742    False
743    False
744    False
745    False
746    False
747    False
748    False
749    False
750    False
751    False
752    False
753    False
754    False
755    False
756    False
757    False
758    False
759    False
760    False
761    False
762    False
763    False
764    False
765    False
766    False
767    False
768    False
769    False
770    False
771    False
772    False
773    False
774    False
775    False
776    False
777    False
778    False
779    False
780    False
781    False
782    False
783    False
784    False
785    False
786    False
787    False
788    False
789    False
790    False
791    False
792    False
793    False
794    False
795    False
796    False
797    False
798    False
799    False
800    False
801    False
802    False
803    False
804    False
805    False
806    False
807    False
808    False
809    False
810    False
811    False
812    False
813    False
814    False
815    False
816    False
817    False
818    False
819    False
820    False
821    False
822    False
823    False
824    False
825    False
826    False
827    False
828    False
829    False
830    False
831    False
832    False
833    False
834    False
835    False
836    False
837    False
838    False
839    False
840    False
841    False
842    False
843    False
844    False
845    False
846    False
847    False
848    False
849    False
850    False
851    False
852    False
853    False
854    False
855    False
856    False
857    False
858    False
859    False
860    False
861    False
862    False
863    False
864    False
865    False
866    False
867    False
868    False
869    False
870    False
871    False
872    False
873    False
874    False
875    False
876    False
877    False
878    False
879    False
880    False
881    False
882    False
883    False
884    False
885    False
886    False
887    False
888    False
889    False
890    False
891    False
892    False
893    False
894    False
895    False
896    False
897    False
898    False
899    False
900    False
901    False
902    False
903    False
904    False
905    False
906    False
907    False
908    False
909    False
910    False
911    False
912    False
913    False
914    False
915    False
916    False
917    False
918    False
919    False
920    False
921    False
922    False
923    False
924    False
925    False
926    False
927    False
928    False
929    False
930    False
931    False
932    False
933    False
934    False
935    False
936    False
937    False
938    False
939    False
940    False
941    False
942    False
943    False
944    False
945    False
946    False
947    False
948    False
949    False
950    False
951    False
952    False
953    False
954    False
955    False
956    False
957    False
958    False
959    False
960    False
961    False
962    False
963    False
964    False
965    False
966    False
967    False
968    False
969    False
970    False
971    False
972    False
973    False
974    False
975    False
976    False
977    False
978    False
979    False
980    False
981    False
982    False
983    False
984    False
985    False
986    False
987    False
988    False
989    False
990    False
991    False
992    False
993    False
994    False
995    False
996    False
997    False
998    False
999    False
dtype: bool

In [1453]:
df_05_17.isnull().sum()

rank                      0
appId                     0
title                     0
url                       0
releaseDate               0
priceText                 1
finalPriceCents           0
discountPercent         100
reviewSummary            21
reviewPercent            21
reviewCount              21
platforms                 0
imageUrl                  0
scrapedAt                 0
currentPlayers           10
developer               499
publisher               501
genres                    0
categories                0
recommendationsTotal    546
metacriticScore         870
shortDescription        497
isFree                  497
type                    497
demandScore               0
qualityScore              0
commercialScore           0
momentumScore             0
opportunityScore          0
marketPosition            0
opportunityType           0
pricingPosition           0
audienceSignal            0
monetizationSignal        0
competitiveSignal         0
intelligenceTags          0
riskFlags                 0
insightSummary            0
recommendedAction         0
dtype: int64

In [1454]:
df_06_02.head()

,rank,appId,title,url,releaseDate,priceText,finalPriceCents,discountPercent,reviewSummary,reviewPercent,...,marketPosition,opportunityType,pricingPosition,audienceSignal,monetizationSignal,competitiveSignal,intelligenceTags,riskFlags,insightSummary,recommendedAction
0,1,730,Counter-Strike 2,https://store.steampowered.com/app/730/Counter...,"Aug 21, 2012",Free,1499,NaN,Very Positive,86.0,...,Breakout leader,Benchmark competitor,Free-to-play,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Counter-Strike 2 is a breakout leader, opportu...","Use as a benchmark for capsule, pricing, tags,..."
1,2,2483190,Forza Horizon 6,https://store.steampowered.com/app/2483190/For...,"May 18, 2026",$69.99,6999,0.0,Very Positive,86.0,...,Breakout leader,Benchmark competitor,High-ticket,Community / multiplayer audience,Paid upfront,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Forza Horizon 6 is a breakout leader, opportun...","Use as a benchmark for capsule, pricing, tags,..."
2,3,359550,Tom Clancy's Rainbow Six Siege,https://store.steampowered.com/app/359550/Tom_...,"Dec 1, 2015",Free,999,NaN,Very Positive,82.0,...,Breakout leader,Benchmark competitor,Free-to-play,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],Tom Clancy's Rainbow Six Siege is a breakout l...,"Use as a benchmark for capsule, pricing, tags,..."
3,4,1675200,Steam Deck,https://store.steampowered.com/app/1675200/Ste...,"Jan 17, 2025",$789.00,39900,0.0,NaN,NaN,...,Non-game / accessory listing,Catalog monitoring,High-ticket,General Steam audience,Paid upfront,Comparable baseline,['non-game-hardware'],"['review-data-missing-or-not-yet-established',...","Steam Deck is a non-game / accessory listing, ...","Keep for catalog awareness, but exclude from g..."
4,5,2694490,Path of Exile 2,https://store.steampowered.com/app/2694490/Pat...,"Dec 6, 2024",$14.99,1499,50.0,Mostly Positive,76.0,...,Breakout leader,Benchmark competitor,Promotional discount,Community / multiplayer audience,Discount-driven sales,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Path of Exile 2 is a breakout leader, opportun...","Use as a benchmark for capsule, pricing, tags,..."

In [1455]:
df_06_02.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   rank                  1000 non-null   int64
 1   appId                 1000 non-null   int64
 2   title                 1000 non-null   str
 3   url                   1000 non-null   str
 4   releaseDate           999 non-null    str
 5   priceText             998 non-null    str
 6   finalPriceCents       1000 non-null   int64
 7   discountPercent       885 non-null    float64
 8   reviewSummary         969 non-null    str
 9   reviewPercent         969 non-null    float64
 10  reviewCount           969 non-null    float64
 11  platforms             1000 non-null   str
 12  imageUrl              1000 non-null   str
 13  scrapedAt             1000 non-null   str
 14  currentPlayers        983 non-null    float64
 15  developer             397 non-null    str
 16  publisher             394 non-null    str
 17  genres                1000 non-null   str
 18  categories            1000 non-null   str
 19  recommendationsTotal  341 non-null    float64
 20  metacriticScore       118 non-null    float64
 21  shortDescription      399 non-null    str
 22  isFree                400 non-null    object
 23  type                  400 non-null    str
 24  demandScore           1000 non-null   int64
 25  qualityScore          1000 non-null   int64
 26  commercialScore       1000 non-null   int64
 27  momentumScore         1000 non-null   int64
 28  opportunityScore      1000 non-null   int64
 29  marketPosition        1000 non-null   str
 30  opportunityType       1000 non-null   str
 31  pricingPosition       1000 non-null   str
 32  audienceSignal        1000 non-null   str
 33  monetizationSignal    1000 non-null   str
 34  competitiveSignal     1000 non-null   str
 35  intelligenceTags      1000 non-null   str
 36  riskFlags             1000 non-null   str
 37  insightSummary        1000 non-null   str
 38  recommendedAction     1000 non-null   str
dtypes: float64(6), int64(8), object(1), str(24)
memory usage: 304.8+ KB

In [1456]:
df_06_02.duplicated()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154    False
155    False
156    False
157    False
158    False
159    False
160    False
161    False
162    False
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172    False
173    False
174    False
175    False
176    False
177    False
178    False
179    False
180    False
181    False
182    False
183    False
184    False
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
205    False
206    False
207    False
208    False
209    False
210    False
211    False
212    False
213    False
214    False
215    False
216    False
217    False
218    False
219    False
220    False
221    False
222    False
223    False
224    False
225    False
226    False
227    False
228    False
229    False
230    False
231    False
232    False
233    False
234    False
235    False
236    False
237    False
238    False
239    False
240    False
241    False
242    False
243    False
244    False
245    False
246    False
247    False
248    False
249    False
250    False
251    False
252    False
253    False
254    False
255    False
256    False
257    False
258    False
259    False
260    False
261    False
262    False
263    False
264    False
265    False
266    False
267    False
268    False
269    False
270    False
271    False
272    False
273    False
274    False
275    False
276    False
277    False
278    False
279    False
280    False
281    False
282    False
283    False
284    False
285    False
286    False
287    False
288    False
289    False
290    False
291    False
292    False
293    False
294    False
295    False
296    False
297    False
298    False
299    False
300    False
301    False
302    False
303    False
304    False
305    False
306    False
307    False
308    False
309    False
310    False
311    False
312    False
313    False
314    False
315    False
316    False
317    False
318    False
319    False
320    False
321    False
322    False
323    False
324    False
325    False
326    False
327    False
328    False
329    False
330    False
331    False
332    False
333    False
334    False
335    False
336    False
337    False
338    False
339    False
340    False
341    False
342    False
343    False
344    False
345    False
346    False
347    False
348    False
349    False
350    False
351    False
352    False
353    False
354    False
355    False
356    False
357    False
358    False
359    False
360    False
361    False
362    False
363    False
364    False
365    False
366    False
367    False
368    False
369    False
370    False
371    False
372    False
373    False
374    False
375    False
376    False
377    False
378    False
379    False
380    False
381    False
382    False
383    False
384    False
385    False
386    False
387    False
388    False
389    False
390    False
391    False
392    False
393    False
394    False
395    False
396    False
397    False
398    False
399    False
400    False
401    False
402    False
403    False
404    False
405    False
406    False
407    False
408    False
409    False
410    False
411    False
412    False
413    False
414    False
415    False
416    False
417    False
418    False
419    False
420    False
421    False
422    False
423    False
424    False
425    False
426    False
427    False
428    False
429    False
430    False
431    False
432    False
433    False
434    False
435    False
436    False
437    False
438    False
439    False
440    False
441    False
442    False
443    False
444    False
445    False
446    False
447    False
448    False
449    False
450    False
451    False
452    False
453    False
454    False
455    False
456    False
457    False
458    False
459    False
460    False
461    False
462    False
463    False
464    False
465    False
466    False
467    False
468    False
469    False
470    False
471    False
472    False
473    False
474    False
475    False
476    False
477    False
478    False
479    False
480    False
481    False
482    False
483    False
484    False
485    False
486    False
487    False
488    False
489    False
490    False
491    False
492    False
493    False
494    False
495    False
496    False
497    False
498    False
499    False
500    False
501    False
502    False
503    False
504    False
505    False
506    False
507    False
508    False
509    False
510    False
511    False
512    False
513    False
514    False
515    False
516    False
517    False
518    False
519    False
520    False
521    False
522    False
523    False
524    False
525    False
526    False
527    False
528    False
529    False
530    False
531    False
532    False
533    False
534    False
535    False
536    False
537    False
538    False
539    False
540    False
541    False
542    False
543    False
544    False
545    False
546    False
547    False
548    False
549    False
550    False
551    False
552    False
553    False
554    False
555    False
556    False
557    False
558    False
559    False
560    False
561    False
562    False
563    False
564    False
565    False
566    False
567    False
568    False
569    False
570    False
571    False
572    False
573    False
574    False
575    False
576    False
577    False
578    False
579    False
580    False
581    False
582    False
583    False
584    False
585    False
586    False
587    False
588    False
589    False
590    False
591    False
592    False
593    False
594    False
595    False
596    False
597    False
598    False
599    False
600    False
601    False
602    False
603    False
604    False
605    False
606    False
607    False
608    False
609    False
610    False
611    False
612    False
613    False
614    False
615    False
616    False
617    False
618    False
619    False
620    False
621    False
622    False
623    False
624    False
625    False
626    False
627    False
628    False
629    False
630    False
631    False
632    False
633    False
634    False
635    False
636    False
637    False
638    False
639    False
640    False
641    False
642    False
643    False
644    False
645    False
646    False
647    False
648    False
649    False
650    False
651    False
652    False
653    False
654    False
655    False
656    False
657    False
658    False
659    False
660    False
661    False
662    False
663    False
664    False
665    False
666    False
667    False
668    False
669    False
670    False
671    False
672    False
673    False
674    False
675    False
676    False
677    False
678    False
679    False
680    False
681    False
682    False
683    False
684    False
685    False
686    False
687    False
688    False
689    False
690    False
691    False
692    False
693    False
694    False
695    False
696    False
697    False
698    False
699    False
700    False
701    False
702    False
703    False
704    False
705    False
706    False
707    False
708    False
709    False
710    False
711    False
712    False
713    False
714    False
715    False
716    False
717    False
718    False
719    False
720    False
721    False
722    False
723    False
724    False
725    False
726    False
727    False
728    False
729    False
730    False
731    False
732    False
733    False
734    False
735    False
736    False
737    False
738    False
739    False
740    False
741    False
742    False
743    False
744    False
745    False
746    False
747    False
748    False
749    False
750    False
751    False
752    False
753    False
754    False
755    False
756    False
757    False
758    False
759    False
760    False
761    False
762    False
763    False
764    False
765    False
766    False
767    False
768    False
769    False
770    False
771    False
772    False
773    False
774    False
775    False
776    False
777    False
778    False
779    False
780    False
781    False
782    False
783    False
784    False
785    False
786    False
787    False
788    False
789    False
790    False
791    False
792    False
793    False
794    False
795    False
796    False
797    False
798    False
799    False
800    False
801    False
802    False
803    False
804    False
805    False
806    False
807    False
808    False
809    False
810    False
811    False
812    False
813    False
814    False
815    False
816    False
817    False
818    False
819    False
820    False
821    False
822    False
823    False
824    False
825    False
826    False
827    False
828    False
829    False
830    False
831    False
832    False
833    False
834    False
835    False
836    False
837    False
838    False
839    False
840    False
841    False
842    False
843    False
844    False
845    False
846    False
847    False
848    False
849    False
850    False
851    False
852    False
853    False
854    False
855    False
856    False
857    False
858    False
859    False
860    False
861    False
862    False
863    False
864    False
865    False
866    False
867    False
868    False
869    False
870    False
871    False
872    False
873    False
874    False
875    False
876    False
877    False
878    False
879    False
880    False
881    False
882    False
883    False
884    False
885    False
886    False
887    False
888    False
889    False
890    False
891    False
892    False
893    False
894    False
895    False
896    False
897    False
898    False
899    False
900    False
901    False
902    False
903    False
904    False
905    False
906    False
907    False
908    False
909    False
910    False
911    False
912    False
913    False
914    False
915    False
916    False
917    False
918    False
919    False
920    False
921    False
922    False
923    False
924    False
925    False
926    False
927    False
928    False
929    False
930    False
931    False
932    False
933    False
934    False
935    False
936    False
937    False
938    False
939    False
940    False
941    False
942    False
943    False
944    False
945    False
946    False
947    False
948    False
949    False
950    False
951    False
952    False
953    False
954    False
955    False
956    False
957    False
958    False
959    False
960    False
961    False
962    False
963    False
964    False
965    False
966    False
967    False
968    False
969    False
970    False
971    False
972    False
973    False
974    False
975    False
976    False
977    False
978    False
979    False
980    False
981    False
982    False
983    False
984    False
985    False
986    False
987    False
988    False
989    False
990    False
991    False
992    False
993    False
994    False
995    False
996    False
997    False
998    False
999    False
dtype: bool

In [1457]:
df_06_02.isnull().sum()

rank                      0
appId                     0
title                     0
url                       0
releaseDate               1
priceText                 2
finalPriceCents           0
discountPercent         115
reviewSummary            31
reviewPercent            31
reviewCount              31
platforms                 0
imageUrl                  0
scrapedAt                 0
currentPlayers           17
developer               603
publisher               606
genres                    0
categories                0
recommendationsTotal    659
metacriticScore         882
shortDescription        601
isFree                  600
type                    600
demandScore               0
qualityScore              0
commercialScore           0
momentumScore             0
opportunityScore          0
marketPosition            0
opportunityType           0
pricingPosition           0
audienceSignal            0
monetizationSignal        0
competitiveSignal         0
intelligenceTags          0
riskFlags                 0
insightSummary            0
recommendedAction         0
dtype: int64

In [1458]:
df_07_02.head()

,rank,appId,title,url,releaseDate,priceText,finalPriceCents,discountPercent,reviewSummary,reviewPercent,...,marketPosition,opportunityType,pricingPosition,audienceSignal,monetizationSignal,competitiveSignal,intelligenceTags,riskFlags,insightSummary,recommendedAction
0,1,4165910,Steam Machine,https://store.steampowered.com/app/4165910/Ste...,"Jun 22, 2026","$1,049.00",104900,0.0,NaN,NaN,...,Non-game / accessory listing,Catalog monitoring,High-ticket,General Steam audience,Paid upfront,Comparablea baseline,"['fresh-release', 'non-game-hardware']","['review-data-missing-or-not-yet-established',...",Steam Machine is aa non-game / accessory listi...,"Keep for catalog awareness, but exclude from g..."
1,2,2767030,Marvel Rivals,https://store.steampowered.com/app/2767030/Mar...,"Dec 5, 2024",Free,0,NaN,Mostly Positive,77.0,...,Commercially aggressive,Pricing/monetization benchmark,Free-to-play,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['high-demand', 'loved-by-players', 'free-to-p...",[],"Marvel Rivals is a commercially aggressive, op...","Compare discount depth, price tier, and moneti..."
2,3,730,Counter-Strike 2,https://store.steampowered.com/app/730/Counter...,"Aug 21, 2012",Free,1499,NaN,Very Positive,86.0,...,Breakout leader,Benchmark competitor,Free-to-play,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Counter-Strike 2 is a breakout leader, opportu...","Use as a benchmark for capsule, pricing, tags,..."
3,4,4704690,MECCHA CHAMELEON,https://store.steampowered.com/app/4704690/MEC...,"Jun 9, 2026",$5.99,599,0.0,Very Positive,89.0,...,Breakout leader,Benchmark competitor,Budget,Community / multiplayer audience,Paid upfront,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"MECCHA CHAMELEON is a breakout leader, opportu...","Use as a benchmark for capsule, pricing, tags,..."
4,5,252490,Rust,https://store.steampowered.com/app/252490/Rust/,"Feb 8, 2018",$19.99,1999,50.0,Very Positive,86.0,...,Breakout leader,Benchmark competitor,Promotional discount,Community / multiplayer audience,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Rust is a breakout leader, opportunity score 9...","Use as a benchmark for capsule, pricing, tags,..."

In [1459]:
df_07_02.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 39 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   rank                  1000 non-null   int64
 1   appId                 1000 non-null   int64
 2   title                 1000 non-null   str
 3   url                   1000 non-null   str
 4   releaseDate           1000 non-null   str
 5   priceText             997 non-null    str
 6   finalPriceCents       1000 non-null   int64
 7   discountPercent       905 non-null    float64
 8   reviewSummary         965 non-null    str
 9   reviewPercent         965 non-null    float64
 10  reviewCount           965 non-null    float64
 11  platforms             1000 non-null   str
 12  imageUrl              1000 non-null   str
 13  scrapedAt             1000 non-null   str
 14  currentPlayers        979 non-null    float64
 15  developer             530 non-null    str
 16  publisher             526 non-null    str
 17  genres                1000 non-null   str
 18  categories            1000 non-null   str
 19  recommendationsTotal  477 non-null    float64
 20  metacriticScore       173 non-null    float64
 21  shortDescription      532 non-null    str
 22  isFree                532 non-null    object
 23  type                  532 non-null    str
 24  demandScore           1000 non-null   int64
 25  qualityScore          1000 non-null   int64
 26  commercialScore       1000 non-null   int64
 27  momentumScore         1000 non-null   int64
 28  opportunityScore      1000 non-null   int64
 29  marketPosition        1000 non-null   str
 30  opportunityType       1000 non-null   str
 31  pricingPosition       1000 non-null   str
 32  audienceSignal        1000 non-null   str
 33  monetizationSignal    1000 non-null   str
 34  competitiveSignal     1000 non-null   str
 35  intelligenceTags      1000 non-null   str
 36  riskFlags             1000 non-null   str
 37  insightSummary        1000 non-null   str
 38  recommendedAction     1000 non-null   str
dtypes: float64(6), int64(8), object(1), str(24)
memory usage: 304.8+ KB

In [1460]:
df_07_02.duplicated()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
102    False
103    False
104    False
105    False
106    False
107    False
108    False
109    False
110    False
111    False
112    False
113    False
114    False
115    False
116    False
117    False
118    False
119    False
120    False
121    False
122    False
123    False
124    False
125    False
126    False
127    False
128    False
129    False
130    False
131    False
132    False
133    False
134    False
135    False
136    False
137    False
138    False
139    False
140    False
141    False
142    False
143    False
144    False
145    False
146    False
147    False
148    False
149    False
150    False
151    False
152    False
153    False
154    False
155    False
156    False
157    False
158    False
159    False
160    False
161    False
162    False
163    False
164    False
165    False
166    False
167    False
168    False
169    False
170    False
171    False
172    False
173    False
174    False
175    False
176    False
177    False
178    False
179    False
180    False
181    False
182    False
183    False
184    False
185    False
186    False
187    False
188    False
189    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
205    False
206    False
207    False
208    False
209    False
210    False
211    False
212    False
213    False
214    False
215    False
216    False
217    False
218    False
219    False
220    False
221    False
222    False
223    False
224    False
225    False
226    False
227    False
228    False
229    False
230    False
231    False
232    False
233    False
234    False
235    False
236    False
237    False
238    False
239    False
240    False
241    False
242    False
243    False
244    False
245    False
246    False
247    False
248    False
249    False
250    False
251    False
252    False
253    False
254    False
255    False
256    False
257    False
258    False
259    False
260    False
261    False
262    False
263    False
264    False
265    False
266    False
267    False
268    False
269    False
270    False
271    False
272    False
273    False
274    False
275    False
276    False
277    False
278    False
279    False
280    False
281    False
282    False
283    False
284    False
285    False
286    False
287    False
288    False
289    False
290    False
291    False
292    False
293    False
294    False
295    False
296    False
297    False
298    False
299    False
300    False
301    False
302    False
303    False
304    False
305    False
306    False
307    False
308    False
309    False
310    False
311    False
312    False
313    False
314    False
315    False
316    False
317    False
318    False
319    False
320    False
321    False
322    False
323    False
324    False
325    False
326    False
327    False
328    False
329    False
330    False
331    False
332    False
333    False
334    False
335    False
336    False
337    False
338    False
339    False
340    False
341    False
342    False
343    False
344    False
345    False
346    False
347    False
348    False
349    False
350    False
351    False
352    False
353    False
354    False
355    False
356    False
357    False
358    False
359    False
360    False
361    False
362    False
363    False
364    False
365    False
366    False
367    False
368    False
369    False
370    False
371    False
372    False
373    False
374    False
375    False
376    False
377    False
378    False
379    False
380    False
381    False
382    False
383    False
384    False
385    False
386    False
387    False
388    False
389    False
390    False
391    False
392    False
393    False
394    False
395    False
396    False
397    False
398    False
399    False
400    False
401    False
402    False
403    False
404    False
405    False
406    False
407    False
408    False
409    False
410    False
411    False
412    False
413    False
414    False
415    False
416    False
417    False
418    False
419    False
420    False
421    False
422    False
423    False
424    False
425    False
426    False
427    False
428    False
429    False
430    False
431    False
432    False
433    False
434    False
435    False
436    False
437    False
438    False
439    False
440    False
441    False
442    False
443    False
444    False
445    False
446    False
447    False
448    False
449    False
450    False
451    False
452    False
453    False
454    False
455    False
456    False
457    False
458    False
459    False
460    False
461    False
462    False
463    False
464    False
465    False
466    False
467    False
468    False
469    False
470    False
471    False
472    False
473    False
474    False
475    False
476    False
477    False
478    False
479    False
480    False
481    False
482    False
483    False
484    False
485    False
486    False
487    False
488    False
489    False
490    False
491    False
492    False
493    False
494    False
495    False
496    False
497    False
498    False
499    False
500    False
501    False
502    False
503    False
504    False
505    False
506    False
507    False
508    False
509    False
510    False
511    False
512    False
513    False
514    False
515    False
516    False
517    False
518    False
519    False
520    False
521    False
522    False
523    False
524    False
525    False
526    False
527    False
528    False
529    False
530    False
531    False
532    False
533    False
534    False
535    False
536    False
537    False
538    False
539    False
540    False
541    False
542    False
543    False
544    False
545    False
546    False
547    False
548    False
549    False
550    False
551    False
552    False
553    False
554    False
555    False
556    False
557    False
558    False
559    False
560    False
561    False
562    False
563    False
564    False
565    False
566    False
567    False
568    False
569    False
570    False
571    False
572    False
573    False
574    False
575    False
576    False
577    False
578    False
579    False
580    False
581    False
582    False
583    False
584    False
585    False
586    False
587    False
588    False
589    False
590    False
591    False
592    False
593    False
594    False
595    False
596    False
597    False
598    False
599    False
600    False
601    False
602    False
603    False
604    False
605    False
606    False
607    False
608    False
609    False
610    False
611    False
612    False
613    False
614    False
615    False
616    False
617    False
618    False
619    False
620    False
621    False
622    False
623    False
624    False
625    False
626    False
627    False
628    False
629    False
630    False
631    False
632    False
633    False
634    False
635    False
636    False
637    False
638    False
639    False
640    False
641    False
642    False
643    False
644    False
645    False
646    False
647    False
648    False
649    False
650    False
651    False
652    False
653    False
654    False
655    False
656    False
657    False
658    False
659    False
660    False
661    False
662    False
663    False
664    False
665    False
666    False
667    False
668    False
669    False
670    False
671    False
672    False
673    False
674    False
675    False
676    False
677    False
678    False
679    False
680    False
681    False
682    False
683    False
684    False
685    False
686    False
687    False
688    False
689    False
690    False
691    False
692    False
693    False
694    False
695    False
696    False
697    False
698    False
699    False
700    False
701    False
702    False
703    False
704    False
705    False
706    False
707    False
708    False
709    False
710    False
711    False
712    False
713    False
714    False
715    False
716    False
717    False
718    False
719    False
720    False
721    False
722    False
723    False
724    False
725    False
726    False
727    False
728    False
729    False
730    False
731    False
732    False
733    False
734    False
735    False
736    False
737    False
738    False
739    False
740    False
741    False
742    False
743    False
744    False
745    False
746    False
747    False
748    False
749    False
750    False
751    False
752    False
753    False
754    False
755    False
756    False
757    False
758    False
759    False
760    False
761    False
762    False
763    False
764    False
765    False
766    False
767    False
768    False
769    False
770    False
771    False
772    False
773    False
774    False
775    False
776    False
777    False
778    False
779    False
780    False
781    False
782    False
783    False
784    False
785    False
786    False
787    False
788    False
789    False
790    False
791    False
792    False
793    False
794    False
795    False
796    False
797    False
798    False
799    False
800    False
801    False
802    False
803    False
804    False
805    False
806    False
807    False
808    False
809    False
810    False
811    False
812    False
813    False
814    False
815    False
816    False
817    False
818    False
819    False
820    False
821    False
822    False
823    False
824    False
825    False
826    False
827    False
828    False
829    False
830    False
831    False
832    False
833    False
834    False
835    False
836    False
837    False
838    False
839    False
840    False
841    False
842    False
843    False
844    False
845    False
846    False
847    False
848    False
849    False
850    False
851    False
852    False
853    False
854    False
855    False
856    False
857    False
858    False
859    False
860    False
861    False
862    False
863    False
864    False
865    False
866    False
867    False
868    False
869    False
870    False
871    False
872    False
873    False
874    False
875    False
876    False
877    False
878    False
879    False
880    False
881    False
882    False
883    False
884    False
885    False
886    False
887    False
888    False
889    False
890    False
891    False
892    False
893    False
894    False
895    False
896    False
897    False
898    False
899    False
900    False
901    False
902    False
903    False
904    False
905    False
906    False
907    False
908    False
909    False
910    False
911    False
912    False
913    False
914    False
915    False
916    False
917    False
918    False
919    False
920    False
921    False
922    False
923    False
924    False
925    False
926    False
927    False
928    False
929    False
930    False
931    False
932    False
933    False
934    False
935    False
936    False
937    False
938    False
939    False
940    False
941    False
942    False
943    False
944    False
945    False
946    False
947    False
948    False
949    False
950    False
951    False
952    False
953    False
954    False
955    False
956    False
957    False
958    False
959    False
960    False
961    False
962    False
963    False
964    False
965    False
966    False
967    False
968    False
969    False
970    False
971    False
972    False
973    False
974    False
975    False
976    False
977    False
978    False
979    False
980    False
981    False
982    False
983    False
984    False
985    False
986    False
987    False
988    False
989    False
990    False
991    False
992    False
993    False
994    False
995    False
996    False
997    False
998    False
999    False
dtype: bool

In [1461]:
df_07_02.isnull().sum()

rank                      0
appId                     0
title                     0
url                       0
releaseDate               0
priceText                 3
finalPriceCents           0
discountPercent          95
reviewSummary            35
reviewPercent            35
reviewCount              35
platforms                 0
imageUrl                  0
scrapedAt                 0
currentPlayers           21
developer               470
publisher               474
genres                    0
categories                0
recommendationsTotal    523
metacriticScore         827
shortDescription        468
isFree                  468
type                    468
demandScore               0
qualityScore              0
commercialScore           0
momentumScore             0
opportunityScore          0
marketPosition            0
opportunityType           0
pricingPosition           0
audienceSignal            0
monetizationSignal        0
competitiveSignal         0
intelligenceTags          0
riskFlags                 0
insightSummary            0
recommendedAction         0
dtype: int64

In [1462]:
# Created a variable to hold the three dataframes for May, June, and July
df_05_to_07 = [(df_05_17, '2026-05-17'),(df_06_02, '2026-06-02'),(df_07_02, '2026-07-02')]

# Combine the three dataframes into one, ignoring the original index to create a new continuous index allowing me to create a developer and publisher lookup table in preparation for the database.
dfs_combined = pd.concat([df_05_17, df_06_02, df_07_02], ignore_index=True)

dfs_combined['releaseDate'].value_counts(dropna=False)

releaseDate
Mar 12, 2026    24
May 14, 2026    21
Oct 23, 2025    21
Apr 30, 2026    20
Jun 18, 2020    19
Jun 2, 2026     17
Apr 16, 2026    16
Dec 4, 2025     16
Mar 5, 2026     13
May 12, 2026    13
Aug 27, 2024    13
Mar 26, 2026    13
May 15, 2026    12
Apr 2, 2026     12
May 21, 2026    12
May 5, 2026     11
Sep 18, 2025    11
Oct 21, 2025    11
Apr 23, 2026    11
Jan 29, 2026    11
May 28, 2026    11
May 1, 2026     10
Jan 30, 2025    10
Mar 31, 2026    10
Dec 2, 2025     10
Dec 7, 2023      9
Mar 17, 2026     9
Mar 3, 2026      9
Feb 5, 2026      9
Oct 27, 2025     9
Jun 17, 2025     9
May 26, 2026     9
May 25, 2026     9
May 18, 2026     8
Apr 14, 2026     8
Sep 4, 2025      8
Sep 25, 2025     8
Jul 22, 2025     8
Jun 23, 2015     8
Apr 10, 2024     8
Jun 19, 2025     8
Aug 7, 2025      8
Apr 9, 2026      8
Oct 27, 2022     8
Apr 28, 2026     7
Apr 27, 2026     7
Apr 28, 2025     7
May 29, 2025     7
Jul 9, 2026      7
Feb 10, 2026     7
Aug 23, 2022     7
Sep 15, 2025     7
Jun 11, 2021     7
Mar 8, 2023      7
May 7, 2026      7
Jan 24, 2019     7
Jun 7, 2024      7
Feb 6, 2026      7
Sep 30, 2025     7
Nov 4, 2025      7
Sep 17, 2020     7
May 4, 2026      7
Dec 10, 2024     7
May 20, 2026     7
Dec 5, 2024      6
Mar 25, 2013     6
Mar 19, 2026     6
Dec 1, 2015      6
Mar 4, 2025      6
Oct 30, 2025     6
Mar 24, 2025     6
May 11, 2026     6
Oct 24, 2023     6
Oct 10, 2007     6
Nov 6, 2025      6
Oct 27, 2016     6
Apr 7, 2026      6
Jun 20, 2024     6
Nov 2, 2023      6
Feb 27, 2025     6
Nov 21, 2024     6
Oct 23, 2023     6
Feb 13, 2026     6
Aug 13, 2013     6
Oct 22, 2025     6
Nov 16, 2018     6
Oct 25, 2022     6
Sep 27, 2022     6
Mar 6, 2025      6
Mar 27, 2025     6
Apr 1, 2024      6
Nov 14, 2019     6
Aug 14, 2025     6
Feb 18, 2026     6
Feb 10, 2025     6
Jun 17, 2024     6
May 17, 2021     6
Apr 18, 2024     6
Oct 20, 2022     6
Sep 23, 2024     6
Oct 8, 2024      6
Sep 26, 2024     6
Aug 11, 2021     6
Mar 13, 2020     6
Sep 16, 2025     6
Oct 19, 2021     6
Sep 24, 2024     6
Jun 1, 2026      6
Jul 15, 2025     6
Jun 16, 2026     6
Jun 11, 2026     6
Oct 10, 2025     5
Nov 13, 2025     5
Sep 11, 2025     5
Jun 16, 2025     5
May 27, 2026     5
Feb 12, 2026     5
May 13, 2026     5
Nov 12, 2024     5
Oct 28, 2025     5
Nov 16, 2023     5
Jul 29, 2025     5
Mar 18, 2026     5
Jan 20, 2022     5
May 9, 2026      5
Sep 19, 2025     5
Feb 11, 2026     5
Oct 24, 2025     5
Nov 18, 2025     5
Jun 18, 2025     5
Apr 3, 2025      5
Oct 10, 2024     5
Jul 27, 2021     5
Jun 4, 2025      5
Mar 28, 2023     5
Sep 9, 2025      5
Aug 24, 2023     5
Dec 3, 2025      5
Apr 29, 2026     5
Jun 13, 2024     5
Aug 4, 2022      5
Oct 14, 2020     5
Apr 1, 2021      5
Aug 17, 2020     5
Jan 22, 2026     5
Aug 27, 2020     5
Sep 17, 2025     5
Apr 8, 2026      5
Oct 9, 2025      5
Jan 31, 2025     5
Mar 21, 2024     5
Sep 11, 2024     5
Feb 21, 2024     5
Jul 2, 2026      5
Jun 13, 2025     5
Mar 20, 2025     5
Aug 1, 2017      5
Jun 23, 2026     5
Jun 25, 2026     5
May 22, 2026     4
Jun 18, 2026     4
Dec 5, 2019      4
Aug 3, 2023      4
May 8, 2024      4
May 23, 2023     4
Dec 13, 2023     4
Feb 26, 2026     4
Feb 11, 2022     4
Feb 19, 2026     4
Jan 24, 2024     4
Feb 3, 2026      4
Mar 13, 2018     4
Sep 10, 2024     4
Sep 5, 2023      4
Dec 5, 2023      4
Aug 1, 2023      4
Mar 6, 2017      4
Jul 25, 2024     4
Sep 25, 2023     4
Oct 18, 2022     4
Nov 3, 2016      4
Mar 12, 2025     4
Dec 14, 2023     4
Mar 10, 2015     4
Jun 28, 2019     4
Oct 29, 2024     4
Sep 23, 2020     4
Oct 12, 2021     4
Mar 30, 2026     4
Jan 25, 2024     4
May 16, 2024     4
Nov 6, 2024      4
Nov 14, 2023     4
Jan 21, 2026     4
Mar 16, 2026     4
Nov 11, 2025     4
Sep 23, 2025     4
May 23, 2025     4
Sep 14, 2017     4
Apr 17, 2025     4
Aug 1, 2024      4
Jun 25, 2025     4
Apr 26, 2024     4
Sep 20, 2018     4
Jan 3, 2017      4
Dec 12, 2017     4
Dec 12, 2018     4
Sep 10, 2025     4
Nov 20, 2025     4
Sep 20, 2023     4
Apr 11, 2024     4
Feb 1, 2024      4
Dec 6, 2022      4
Mar 28, 2017     4
Jun 5, 2026      4
Jun 11, 2019     4
Oct 4, 2024      4
Jul 17, 2025     4
Feb 2, 2023      4
Mar 10, 2023     4
Sep 24, 2025     4
Jul 23, 2024     4
Aug 27, 2025     4
Jan 19, 2023     4
Jun 10, 2026     4
Aug 21, 2012     3
Nov 4, 2020      3
Jan 23, 2018     3
May 13, 2021     3
Aug 10, 2023     3
Feb 2, 2016      3
Nov 5, 2015      3
May 8, 2018      3
Aug 15, 2013     3
Jun 14, 2016     3
Feb 8, 2018      3
Feb 8, 2024      3
Nov 14, 2025     3
Feb 24, 2022     3
Apr 27, 2015     3
Dec 6, 2024      3
Feb 26, 2016     3
May 8, 2026      3
Feb 18, 2014     3
May 22, 2017     3
Feb 26, 2025     3
Mar 25, 2024     3
May 6, 2026      3
Sep 19, 2023     3
Feb 1, 2017      3
Jul 21, 2020     3
May 9, 2016      3
Sep 18, 2020     3
Apr 30, 2024     3
Feb 4, 2025      3
Apr 14, 2020     3
Sep 3, 2020      3
May 24, 2017     3
Oct 25, 2023     3
Dec 21, 2017     3
Oct 17, 2018     3
Dec 9, 2020      3
Oct 1, 2019      3
Apr 24, 2025     3
May 29, 2015     3
Nov 16, 2022     3
Mar 7, 2019      3
May 28, 2024     3
Feb 23, 2023     3
Oct 15, 2023     3
Sep 1, 2020      3
Jun 10, 2025     3
Jun 26, 2014     3
Jan 12, 2015     3
Apr 28, 2021     3
Nov 20, 2024     3
Apr 21, 2022     3
Aug 11, 2020     3
May 13, 2020     3
Nov 15, 2025     3
Jun 6, 2016      3
Feb 22, 2024     3
Aug 14, 2020     3
Feb 26, 2023     3
Nov 8, 2013      3
Feb 15, 2024     3
Nov 4, 2014      3
Dec 13, 2018     3
Jun 20, 2022     3
Nov 19, 2024     3
Jun 3, 2020      3
Feb 16, 2022     3
Nov 15, 2017     3
Dec 3, 2021      3
Aug 9, 2012      3
Sep 9, 2024      3
Jul 9, 2013      3
Jul 9, 2024      3
Dec 17, 2018     3
Oct 2, 2025      3
Jan 18, 2024     3
Mar 5, 2024      3
Aug 12, 2016     3
Apr 21, 2026     3
May 16, 2011     3
Nov 24, 2025     3
Aug 31, 2020     3
Jun 5, 2015      3
Jan 18, 2022     3
Nov 30, 2022     3
Dec 3, 2019      3
Oct 1, 2024      3
Feb 13, 2017     3
Nov 9, 2015      3
Jun 11, 2020     3
Nov 8, 2011      3
Mar 7, 2025      3
Aug 28, 2017     3
Aug 27, 2019     3
Jan 16, 2026     3
Jan 31, 2024     3
May 2, 2023      3
May 27, 2021     3
Aug 11, 2022     3
Jun 30, 2024     3
Feb 16, 2017     3
Apr 15, 2025     3
Dec 19, 2014     3
Oct 17, 2017     3
Oct 28, 2021     3
Jun 1, 2023      3
Nov 29, 2006     3
Jan 12, 2023     3
Dec 4, 2024      3
Nov 16, 2009     3
Aug 14, 2024     3
Sep 19, 2024     3
Oct 12, 2012     3
Sep 6, 2018      3
Apr 16, 2019     3
Dec 22, 2014     3
Feb 2, 2021      3
Jan 30, 2026     3
Jun 16, 2023     3
Feb 18, 2016     3
Feb 20, 2024     3
Dec 2, 2021      3
Aug 19, 2024     3
Oct 21, 2024     3
Aug 27, 2017     3
Apr 22, 2025     3
Oct 26, 2017     3
Nov 5, 2019      3
Apr 20, 2026     3
Jul 11, 2025     3
Sep 18, 2019     3
Apr 11, 2016     3
Sep 12, 2013     3
Nov 9, 2010      3
Feb 28, 2019     3
Jan 31, 2012     3
Sep 4, 2024      3
Apr 27, 2023     3
Nov 8, 2021      3
Sep 29, 2017     3
Jun 11, 2025     3
Jul 15, 2022     3
May 29, 2019     3
Jun 24, 2025     3
Sep 15, 2024     3
Feb 10, 2023     3
Sep 21, 2023     3
Aug 12, 2022     3
Jul 14, 2022     3
Nov 12, 2012     3
Oct 21, 2022     3
Nov 11, 2009     3
Aug 2, 2013      3
Oct 7, 2019      3
Nov 1, 2024      3
Nov 26, 2025     3
Sep 28, 2017     3
Mar 21, 2019     3
Mar 13, 2023     3
Apr 4, 2018      3
Oct 20, 2016     3
Jan 6, 2026      3
Apr 23, 2024     3
Jan 12, 2026     3
Apr 21, 2016     3
Aug 22, 2025     3
Feb 13, 2018     3
Sep 18, 2023     3
Sep 28, 2023     3
Apr 30, 2018     3
Feb 24, 2017     3
Mar 19, 2025     3
May 23, 2018     3
Aug 22, 2024     3
Oct 18, 2016     3
Nov 12, 2025     3
Sep 26, 2012     3
Mar 13, 2026     3
May 16, 2018     3
Mar 6, 2026      3
May 19, 2020     3
Mar 30, 2021     3
Oct 19, 2010     3
Jul 10, 2025     3
May 26, 2021     3
Oct 2, 2024      3
Apr 10, 2025     3
Jul 2, 2024      3
Aug 24, 2015     3
Sep 26, 2025     3
May 18, 2015     3
Nov 18, 2008     3
Nov 17, 2021     3
Apr 18, 2011     3
Nov 15, 2022     3
Oct 28, 2024     3
Jan 1, 2023      3
Jan 23, 2019     3
Sep 23, 2021     3
Oct 13, 2023     3
Nov 10, 2021     3
Apr 4, 2024      3
Jun 28, 2022     3
Jul 3, 2025      3
Oct 24, 2024     3
Mar 30, 2023     3
Dec 8, 2021      3
Jul 25, 2023     3
Aug 20, 2024     3
Sep 3, 2019      3
Jan 27, 2011     3
Aug 7, 2018      3
Jun 19, 2024     3
Oct 30, 2015     3
Jun 14, 2011     3
Jun 24, 2022     3
Jun 6, 2012      3
Jun 28, 2023     3
Jan 23, 2017     3
May 20, 2025     3
Mar 24, 2020     3
Jun 12, 2022     3
Feb 24, 2021     3
Feb 13, 2025     3
May 24, 2016     3
Nov 9, 2016      3
Oct 17, 2016     3
Feb 5, 2019      3
Jan 7, 2024      3
May 23, 2024     3
Dec 10, 2025     3
Aug 28, 2025     3
Feb 25, 2016     3
Sep 2, 2013      3
Apr 2, 2015      3
Mar 12, 2015     3
Dec 9, 2022      3
Aug 22, 2023     3
Jun 17, 2022     3
Mar 5, 2020      3
Jun 30, 2020     3
Sep 17, 2012     3
Sep 21, 2020     3
Sep 15, 2015     3
Aug 5, 2024      3
Mar 4, 2016      3
May 5, 2025      3
Sep 29, 2022     3
Jun 28, 2024     3
Nov 2, 2011      3
Jan 14, 2022     3
Mar 24, 2021     3
Nov 30, 2018     3
Apr 5, 2022      3
Aug 5, 2020      3
Sep 22, 2021     3
Sep 24, 2020     3
Nov 20, 2023     3
Oct 15, 2019     3
Aug 9, 2018      3
Mar 8, 2018      3
Nov 17, 2008     3
Dec 9, 2021      3
Jun 23, 2023     3
Jul 20, 2021     3
Sep 22, 2025     3
Sep 2, 2021      3
Dec 1, 2023      3
Jun 6, 2025      3
Dec 6, 2018      3
Oct 15, 2025     3
Feb 24, 2020     3
Apr 10, 2026     3
Mar 27, 2019     3
Jul 16, 2024     3
Sep 21, 2010     3
Jul 30, 2019     3
Aug 11, 2025     3
Sep 1, 2015      3
Dec 16, 2021     3
Mar 1, 2022      3
Sep 29, 2021     3
Oct 9, 2017      3
Nov 8, 2022      3
Apr 12, 2023     3
Mar 10, 2026     3
Dec 8, 2023      3
Feb 20, 2023     3
Aug 6, 2018      3
Oct 18, 2018     3
Apr 1, 2025      3
May 16, 2022     3
Oct 23, 2024     3
Aug 6, 2026      3
Mar 19, 2020     3
Aug 15, 2018     3
Feb 22, 2022     3
Jan 31, 2019     3
Nov 12, 2009     3
Jan 26, 2023     3
Jul 19, 2022     3
Sep 1, 2022      3
Dec 13, 2022     3
May 7, 2021      3
Aug 7, 2020      3
Dec 8, 2024      3
Aug 10, 2021     3
Nov 1, 2021      3
Sep 24, 2026     3
Aug 13, 2026     3
Apr 24, 2018     3
Apr 27, 2022     3
May 9, 2024      3
May 30, 2023     3
Jan 23, 2025     3
Nov 14, 2024     3
Oct 16, 2025     3
Aug 25, 2014     3
Oct 31, 2024     3
Apr 3, 2015      2
Apr 23, 2019     2
Jan 24, 2013     2
Mar 26, 2018     2
Sep 21, 2021     2
Apr 13, 2015     2
May 30, 2019     2
Sep 9, 2010      2
Nov 2, 2017      2
Oct 22, 2014     2
Oct 6, 2022      2
Apr 6, 2023      2
Dec 1, 2025      2
Jun 18, 2024     2
Aug 15, 2025     2
Oct 29, 2025     2
Jan 26, 2018     2
Mar 25, 2014     2
Mar 25, 2021     2
Oct 17, 2024     2
Nov 10, 2022     2
Oct 23, 2013     2
May 9, 2023      2
Mar 13, 2025     2
Apr 24, 2026     2
Jan 9, 2024      2
Nov 3, 2014      2
May 30, 2025     2
Dec 17, 2021     2
Aug 13, 2025     2
Jul 26, 2023     2
Jun 15, 2025     2
Jun 25, 2012     2
May 21, 2019     2
Dec 28, 2018     2
May 6, 2025      2
Oct 5, 2018      2
May 8, 2020      2
Apr 1, 2026      2
Apr 2, 2024      2
Aug 6, 2025      2
Aug 8, 2024      2
Feb 20, 2012     2
Nov 17, 2014     2
May 26, 2014     2
May 25, 2010     2
May 27, 2025     2
Nov 10, 2023     2
Feb 4, 2026      2
May 17, 2018     2
Sep 15, 2009     2
Jul 1, 2021      2
Sep 17, 2015     2
Apr 3, 2018      2
Aug 29, 2024     2
Jul 23, 2019     2
Nov 30, 2023     2
Jul 28, 2020     2
Nov 17, 2025     2
May 14, 2021     2
Dec 8, 2017      2
Feb 4, 2016      2
May 17, 2022     2
Jan 9, 2014      2
Jan 27, 2025     2
May 8, 2023      2
Jan 15, 2025     2
Apr 5, 2020      2
Apr 1, 2015      2
Oct 15, 2020     2
Aug 16, 2022     2
Sep 13, 2018     2
Dec 8, 2025      2
Mar 29, 2017     2
Jul 14, 2023     2
Aug 15, 2024     2
May 31, 2022     2
Oct 6, 2026      2
Jan 27, 2023     2
Mar 23, 2020     2
Feb 29, 2016     2
May 7, 2024      2
Nov 3, 2023      2
Jan 31, 2017     2
Feb 6, 2020      2
Oct 5, 2020      2
Sep 20, 2022     2
Dec 17, 2022     2
Nov 27, 2025     2
Aug 2, 2024      2
Apr 13, 2026     2
Mar 8, 2024      2
Oct 8, 2015      2
Feb 3, 2022      2
Oct 6, 2015      2
Nov 18, 2022     2
Feb 18, 2025     2
Jan 21, 2022     2
Mar 26, 2019     2
Sep 5, 2019      2
Aug 31, 2022     2
May 28, 2025     2
Feb 22, 2016     2
Nov 11, 2014     2
Oct 6, 2014      2
Jul 8, 2025      2
Mar 21, 2013     2
Aug 23, 2021     2
Dec 17, 2009     2
Feb 15, 2023     2
Jan 17, 2025     2
Oct 1, 2026      2
Sep 5, 2024      2
Aug 26, 2025     2
Sep 9, 2019      2
Sep 17, 2026     2
Feb 2, 2026      2
Oct 13, 2026     2
Apr 22, 2024     2
May 29, 2026     2
Feb 14, 2020     2
Jul 12, 2018     2
Jun 23, 2025     2
Dec 4, 2020      2
Jun 4, 2024      2
Feb 1, 2022      2
Apr 9, 2019      2
Jan 25, 2018     2
Oct 13, 2022     2
Jun 9, 2022      2
Nov 9, 2021      2
Oct 11, 2017     2
Jul 22, 2021     2
Jun 16, 2009     2
Dec 1, 2020      2
Sep 28, 2021     2
Oct 17, 2022     2
Jun 29, 2023     2
Oct 16, 2017     2
Mar 24, 2017     2
Feb 9, 2016      2
Jan 27, 2026     2
Oct 24, 2013     2
Jan 23, 2023     2
Jun 16, 2022     2
Feb 28, 2023     2
Jun 25, 2024     2
Apr 9, 2018      2
Oct 7, 2024      2
Aug 12, 2025     2
Mar 17, 2017     2
Sep 14, 2023     2
May 14, 2025     2
Sep 3, 2025      2
Dec 25, 2020     2
Nov 7, 2022      2
Jun 22, 2026     2
Jun 9, 2026      2
Jun 29, 2026     2
Oct 22, 2026     2
Jun 4, 2026      2
May 12, 2016     2
Apr 13, 2023     2
Jun 26, 2026     2
Sep 18, 2024     2
Sep 23, 2019     1
Apr 18, 2023     1
Jun 20, 2025     1
May 15, 2017     1
Dec 15, 2010     1
Nov 18, 2016     1
May 7, 2020      1
Apr 15, 2019     1
Jun 22, 2018     1
Oct 21, 2021     1
Jul 24, 2012     1
Aug 2, 2018      1
Nov 17, 2017     1
Oct 9, 2018      1
Oct 8, 2019      1
Sep 12, 2024     1
Oct 22, 2024     1
Apr 19, 2013     1
Sep 16, 2024     1
Mar 31, 2016     1
Apr 1, 2023      1
Aug 29, 2025     1
Aug 7, 2024      1
Mar 9, 2026      1
Aug 17, 2021     1
Mar 4, 2026      1
Aug 2, 2023      1
Dec 5, 2013      1
Dec 4, 2023      1
Jul 22, 2016     1
May 18, 2023     1
Sep 23, 2022     1
Apr 7, 2022      1
May 9, 2019      1
Mar 9, 2015      1
Nov 4, 2022      1
Oct 4, 2018      1
Nov 21, 2021     1
Oct 21, 2008     1
Jul 19, 2023     1
Jul 24, 2025     1
Jan 6, 2022      1
Nov 14, 2022     1
Mar 19, 2024     1
Oct 3, 2023      1
Jul 16, 2020     1
Dec 16, 2025     1
Mar 22, 2007     1
Nov 19, 2013     1
Dec 15, 2009     1
May 1, 2018      1
Jun 29, 2018     1
Mar 23, 2021     1
Nov 9, 2017      1
Nov 12, 2020     1
May 1, 2025      1
Jan 10, 2026     1
Dec 19, 2008     1
Nov 8, 2025      1
Oct 9, 2023      1
Nov 7, 2019      1
Jun 24, 2013     1
Dec 11, 2025     1
Apr 8, 2022      1
May 2, 2024      1
Nov 12, 2007     1
Oct 31, 2022     1
Jun 28, 2018     1
May 13, 2016     1
Sep 26, 2019     1
Dec 12, 2025     1
Dec 18, 2025     1
Jun 30, 2021     1
Oct 13, 2021     1
Feb 25, 2025     1
Sep 7, 2021      1
Oct 16, 2019     1
Jun 22, 2023     1
Sep 30, 2021     1
May 17, 2023     1
Jul 27, 2017     1
Aug 10, 2022     1
May 15, 2024     1
Mar 15, 2011     1
Jan 26, 2021     1
May 5, 2009      1
Aug 14, 2018     1
Sep 1, 2021      1
Mar 15, 2022     1
Feb 17, 2022     1
Jan 30, 2024     1
Coming soon      1
Feb 12, 2027     1
Sep 23, 2026     1
Jul 6, 2025      1
Jan 19, 2026     1
May 24, 2022     1
Feb 21, 2025     1
Apr 28, 2020     1
Sep 30, 2026     1
Mar 22, 2025     1
Nov 18, 2015     1
Nov 25, 2025     1
Jan 26, 2016     1
Sep 4, 2013      1
Apr 28, 2022     1
Nov 8, 2024      1
Nov 25, 2024     1
May 19, 2026     1
Apr 2, 2018      1
Jul 18, 2025     1
Feb 16, 2012     1
Apr 23, 2025     1
Dec 8, 2022      1
Apr 24, 2017     1
May 5, 2022      1
Nov 5, 2020      1
Sep 14, 2018     1
Dec 15, 2020     1
Sep 27, 2024     1
Jun 26, 2025     1
Dec 7, 2022      1
Feb 25, 2019     1
Jul 26, 2017     1
Sep 5, 2022      1
Jul 1, 2025      1
Nov 30, 2015     1
Mar 13, 2019     1
Mar 29, 2019     1
Oct 11, 2013     1
Apr 7, 2025      1
Oct 8, 2014      1
May 13, 2025     1
May 31, 2018     1
Nov 27, 2012     1
NaN              1
Aug 10, 2018     1
Aug 3, 2017      1
Mar 28, 2016     1
May 18, 2022     1
Aug 2, 2016      1
May 31, 2012     1
Apr 8, 2024      1
Jun 6, 2023      1
Jan 5, 2026      1
Jan 21, 2020     1
Dec 25, 2023     1
Dec 7, 2017      1
May 5, 2020      1
Jan 20, 2021     1
Feb 25, 2026     1
Apr 8, 2014      1
Jan 23, 2026     1
Aug 26, 2021     1
May 15, 2023     1
Jun 22, 2012     1
Sep 15, 2021     1
Oct 20, 2021     1
Aug 8, 2017      1
Jul 18, 2024     1
Sep 2, 2026      1
Apr 3, 2026      1
Oct 5, 2021      1
Oct 24, 2022     1
Aug 3, 2016      1
Dec 11, 2018     1
Jun 4, 2018      1
Mar 3, 2014      1
Oct 26, 2021     1
Sep 5, 2011      1
Jun 2, 2025      1
Aug 20, 2020     1
Jul 23, 2026     1
Jul 28, 2026     1
Nov 28, 2016     1
Nov 6, 2023      1
Sep 20, 2024     1
Mar 24, 2022     1
Oct 8, 2012      1
Sep 17, 2024     1
Jul 23, 2020     1
May 11, 2023     1
Oct 19, 2022     1
Jun 14, 2018     1
Feb 22, 2019     1
Jun 24, 2026     1
Dec 27, 2019     1
Aug 27, 2026     1
Jun 8, 2026      1
May 14, 2019     1
Sep 5, 2025      1
Feb 23, 2027     1
Jun 7, 2019      1
May 25, 2021     1
Aug 28, 2023     1
Jun 3, 2026      1
Mar 30, 2022     1
Jan 25, 2023     1
Feb 24, 2023     1
Mar 28, 2025     1
Dec 15, 2025     1
Jun 13, 2020     1
Jan 12, 2022     1
Mar 11, 2024     1
Mar 16, 2022     1
Oct 23, 2012     1
Jan 28, 2021     1
Oct 29, 2020     1
Jan 25, 2022     1
Dec 9, 2025      1
Mar 21, 2025     1
Oct 14, 2021     1
Apr 23, 2021     1
Apr 25, 2024     1
Oct 20, 2025     1
Mar 11, 2026     1
Apr 27, 2017     1
Oct 16, 2024     1
Nov 11, 2016     1
Oct 8, 2026      1
Dec 11, 2017     1
Aug 18, 2023     1
Sep 8, 2026      1
Mar 6, 2018      1
Sep 12, 2014     1
Feb 17, 2027     1
Jan 16, 2020     1
Dec 1, 2022      1
Feb 17, 2015     1
Jul 15, 2019     1
Dec 4, 2012      1
May 25, 2022     1
Jun 14, 2025     1
Mar 11, 2020     1
Oct 1, 2015      1
May 23, 2019     1
Feb 15, 2019     1
Oct 5, 2017      1
May 4, 2017      1
Jun 17, 2026     1
Feb 1, 2018      1
May 26, 2022     1
Feb 20, 2025     1
Jan 16, 2025     1
Jun 21, 2023     1
Feb 5, 2025      1
Oct 27, 2015     1
Mar 25, 2020     1
Feb 14, 2024     1
Sep 14, 2025     1
Sep 28, 2022     1
Oct 14, 2026     1
Feb 23, 2022     1
Jul 1, 2026      1
May 21, 2024     1
Jul 31, 2025     1
Aug 8, 2013      1
Jul 23, 2025     1
Mar 5, 2025      1
Sep 8, 2020      1
Jan 9, 2020      1
Aug 30, 2022     1
Aug 29, 2017     1
Mar 10, 2020     1
Jan 8, 2025      1
May 21, 2025     1
Sep 10, 2019     1
Apr 23, 2013     1
Jun 15, 2021     1
Jan 19, 2016     1
Nov 7, 2024      1
May 15, 2014     1
Apr 11, 2017     1
Jun 4, 2020      1
Apr 25, 2017     1
Dec 7, 2021      1
Nov 17, 2016     1
Nov 29, 2023     1
Sep 13, 2021     1
Name: count, dtype: int64

In [1463]:
#While checking my release date nulls I found Vale Index replecement tether which is not a game so I added it to the list of titles to drop below
dfs_combined.loc[dfs_combined['releaseDate'].isna(),['title', 'releaseDate']]

                                title releaseDate
1733  Valve Index® Replacement Tether         NaN

In [1464]:

#Created a for loop to iterate through the list of dataframes and perform the following operations on each dataframe:
for df, snapshot_date in df_05_to_07:
    df.drop(columns=['recommendationsTotal', 'metacriticScore', 'shortDescription', 'isFree', 'recommendedAction'], inplace=True)

     #The dataframes are being renamed to have a 'tags' column instead of 'categories' as the content of that column are labled as 'tags' in the Steam store
    #Renamed the 'appId' column to 'appID' to match the naming convention of the other columns in the dataframe
    df.rename(columns={'categories': 'tags'}, inplace=True)
    df.rename(columns={'appId' : 'appID'}, inplace=True)


    #Droping the Steam Machine, Steam Deck, and EA Play from the dataset as they are not games 
    df.drop(df[df['title'].isin(['Steam Machine', 'Steam Deck', 'EA Play', 'Replacement Tether'])].index, inplace=True)
    #Data contained a 'type' coulumn for things like DLC, Software, and Hardware. I only needed those labled as 'games' so I dropped the rest of the rows that were not labled as 'games'
    df.drop(df[df['type'] != 'game'].index, inplace=True)

    #dropping the row for the Call of Duty launcher by the appID to insure that the other Call of Duty's are not droped as they are the actual games 
    df.drop(df[df['appID'] == 1938090].index, inplace=True) 

    #Updating the missing publisher manually due to it being the only one missing 
    #Puiblisher was originally Nuverse (2022–2025) but the current publisher for the game is Skystone Games as of 2025 
        #-- [Marvel Snap - Wikipedia](https://en.wikipedia.org/wiki/Marvel_Snap)
    df.loc[df['appID'] == 1997040, 'publisher'] = 'Skystone Games'

    #I found the release date for Rayman Legends Retold and updated the missing release date in the dataframe. The game is set to be released on October 1, 2026
    #-- [Rayman Legends Retold — Ubisoft](https://www.ubisoft.com/en-us/games/rayman-legends-retold)
    df.loc[df['appID'] == 4084710, 'releaseDate'] = 'Oct 1, 2026' 


    # Reset the DataFrame index
    df.reset_index(drop=True, inplace=True)

    # Renumbered the rank column to follow the ranking of just the games
    df['rank'] = range(1, len(df) + 1)



    #Changing the data type of the 'releaseDate' column to a datetime object for easier manipulation and analysis
    # The 'snapshotDate' column is being created to hold the date of the snapshot to allow for some nulls as some games may not have released as of the snapshot date but still be in the top 1000 list of games on Steam counting their pre order sales
    df['releaseDate'] = pd.to_datetime(df['releaseDate'],format='%b %d, %Y', errors='coerce')
    df['snapshotDate'] = pd.Timestamp(snapshot_date)

    #Creating a new column to show if a game has been releaseed as of the snapshot date. This will be a boolean value where True means the game has been released and False means it has not been released yet
    df['releasedYet'] = (df['releaseDate'] <= df['snapshotDate'])

    # Changing the data type of the scrapedAt column to datetime as I noticed the data was ISO 8601 format but stored as a string 
    df['scrapedAt'] = pd.to_datetime(df['scrapedAt'], format='ISO8601')

    #The genres shown in the data appear to be formated as list, due to this I imported ast and decided to change the current type, str, to list
    df['genres'] = df['genres'].apply(ast.literal_eval)

In [1465]:
#Recombinging so that I can add the snapshotID that requires the snapshotDate column to be in the dataframe
dfs_combined = pd.concat([df_05_17, df_06_02, df_07_02], ignore_index=True)

dev_lookup = (dfs_combined[['developer']].drop_duplicates().sort_values('developer').reset_index(drop=True))
dev_lookup['developerID'] = dev_lookup.index + 1

publisher_lookup = (dfs_combined[['publisher']].drop_duplicates().sort_values('publisher').reset_index(drop=True))
publisher_lookup['publisherID'] = publisher_lookup.index + 1

snapshot_lookup = dfs_combined[['snapshotDate']].drop_duplicates().sort_values('snapshotDate').reset_index(drop=True)
snapshot_lookup['snapshotID'] = snapshot_lookup.index + 1

genre_lookup = (dfs_combined[['genres']].explode('genres').drop_duplicates().sort_values('genres').reset_index(drop=True))
genre_lookup['genreID'] = genre_lookup.index + 1

for df, snapshot_date in df_05_to_07:
    # Mapped developer and publisher names to their respective IDs
        df['developerID'] = df['developer'].map(dev_lookup.set_index('developer')['developerID'])
        df['publisherID'] = df['publisher'].map(publisher_lookup.set_index('publisher')['publisherID'])
        df['snapshotID'] = df['snapshotDate'].map(snapshot_lookup.set_index('snapshotDate')['snapshotID'])
        

#Recombining the three dataframes into one to include the developer and publisher ID columns for the database
dfs_combined = pd.concat([df_05_17, df_06_02, df_07_02], ignore_index=True)

In [1466]:
dfs_combined['genres']

0                       [Action, Adventure, Early Access]
1                            [Racing, Simulation, Sports]
2                                  [Action, Free To Play]
3                                  [Action, Free To Play]
4                                     [Action, Adventure]
5                          [Adventure, Indie, Simulation]
6                [Action, Adventure, Indie, Early Access]
7                       [Action, Adventure, Free To Play]
8                                      [Adventure, Indie]
9       [Action, Adventure, Casual, Massively Multipla...
10                 [Action, Adventure, RPG, Early Access]
11                            [Action, RPG, Free To Play]
12                                               [Sports]
13                                     [Adventure, Indie]
14                                    [Action, Adventure]
15      [Action, Massively Multiplayer, Simulation, St...
16                                 [Action, Free To Play]
17                                    [Indie, Simulation]
18                          [Action, Indie, Early Access]
19                                    [Action, Adventure]
20                                 [Action, Free To Play]
21      [Action, Adventure, Massively Multiplayer, RPG...
22                        [Indie, Strategy, Early Access]
23                                               [Action]
24                                    [Action, Adventure]
25      [Action, Massively Multiplayer, Simulation, Fr...
26                                               [Action]
27                            [Action, Adventure, Racing]
28      [Action, Adventure, Indie, Massively Multiplay...
29                                               [Action]
30                                               [Action]
31                             [Adventure, RPG, Strategy]
32                                    [Action, Adventure]
33                 [Action, Adventure, RPG, Free To Play]
34             [Action, Adventure, Massively Multiplayer]
35                                          [Action, RPG]
36                                    [Indie, Simulation]
37      [Action, Adventure, Massively Multiplayer, RPG...
38                 [Action, Adventure, RPG, Free To Play]
39      [Action, Indie, Simulation, Strategy, Early Ac...
40                               [Indie, RPG, Simulation]
41                                               [Action]
42                               [Action, Adventure, RPG]
43                  [Action, Indie, Simulation, Strategy]
44                               [Strategy, Free To Play]
45                           [Massively Multiplayer, RPG]
46        [Action, Adventure, Massively Multiplayer, RPG]
47          [Adventure, Casual, Simulation, Free To Play]
48                             [Action, Adventure, Indie]
49                                 [Action, Early Access]
50                                    [Action, Adventure]
51      [Adventure, Casual, Indie, RPG, Simulation, Fr...
52                             [Action, Adventure, Indie]
53                 [Action, Adventure, RPG, Early Access]
54                                               [Action]
55      [Action, Adventure, Indie, Massively Multiplay...
56                     [Casual, Simulation, Early Access]
57      [Adventure, Casual, Massively Multiplayer, Sim...
58                                 [Action, Free To Play]
59             [Massively Multiplayer, RPG, Free To Play]
60                                 [Simulation, Strategy]
61                          [Action, Indie, Early Access]
62                                    [Action, Adventure]
63      [Action, Massively Multiplayer, Simulation, Ea...
64                     [Indie, RPG, Simulation, Strategy]
65                            [Casual, Indie, Simulation]
66      [Action, Adventure, Indie, Massively Multiplay...
67                               [Action, Adventure, RPG]
68                                        [Action, Indie]
69                                                  [RPG]
70                         [Adventure, Indie, Simulation]
71                                   [Simulation, Sports]
72                          [Action, Indie, Early Access]
73      [Action, Adventure, Massively Multiplayer, RPG...
74                          [RPG, Strategy, Early Access]
75      [Action, Adventure, Indie, Massively Multiplay...
76      [Action, Adventure, Massively Multiplayer, Fre...
77                                           [Simulation]
78                          [Indie, Simulation, Strategy]
79                                           [Simulation]
80                                                  [RPG]
81                      [Action, Adventure, Free To Play]
82                                 [Action, Free To Play]
83                                 [Action, Free To Play]
84                               [Action, Adventure, RPG]
85                                          [Action, RPG]
86                     [Racing, Simulation, Early Access]
87                                 [Action, Free To Play]
88      [Action, Adventure, Massively Multiplayer, RPG...
89                                               [Action]
90                             [Action, Adventure, Indie]
91                                [Casual, Indie, Sports]
92                                     [Action, Strategy]
93              [Action, Indie, Simulation, Early Access]
94      [Action, Adventure, Indie, Simulation, Early A...
95                            [RPG, Simulation, Strategy]
96                         [Action, Simulation, Strategy]
97                                                  [RPG]
98        [Action, Adventure, Massively Multiplayer, RPG]
99                            [Casual, Indie, Simulation]
100                            [Action, Adventure, Indie]
101                                         [Action, RPG]
102     [Massively Multiplayer, Racing, Simulation, Sp...
103                                              [Action]
104     [Action, Massively Multiplayer, Simulation, Fr...
105                              [Action, Adventure, RPG]
106                     [Action, Adventure, Early Access]
107     [Adventure, Indie, RPG, Simulation, Early Access]
108                 [Action, Indie, Simulation, Strategy]
109                                       [Action, Indie]
110         [Action, Adventure, Indie, RPG, Early Access]
111                                              [Action]
112      [Action, Massively Multiplayer, RPG, Simulation]
113                                [Simulation, Strategy]
114                       [Action, Adventure, Indie, RPG]
115                [Action, Adventure, Indie, Simulation]
116                 [Casual, Indie, Simulation, Strategy]
117                                                    []
118                            [Action, Adventure, Indie]
119                [Indie, RPG, Simulation, Early Access]
120                       [Action, Adventure, Indie, RPG]
121                                   [Action, Adventure]
122                                       [Action, Indie]
123                                              [Action]
124                            [Action, Adventure, Indie]
125            [Action, Adventure, Massively Multiplayer]
126                        [Adventure, Indie, Simulation]
127                                          [Simulation]
128                                   [Action, Adventure]
129                                    [Action, Strategy]
130                  [Action, Adventure, RPG, Simulation]
131     [Action, Massively Multiplayer, Simulation, St...
132                       [Action, Adventure, Simulation]
133                                   [Action, Adventure]
134                                   [Action, Adventure]
135                                   [Action, Adventure]
136     [Action, Adventure, Casual, Massively Multipla...
137                                [Action, Early Access]
138                                              [Action]
139                           [Casual, Indie, Simulation]
140                                              [Action]
141                                              [Action]
142                              [Action, Adventure, RPG]
143                      [Action, Strategy, Free To Play]
144     [Action, Adventure, RPG, Simulation, Strategy,...
145                                            [Strategy]
146                                   [Action, Adventure]
147              [Adventure, Indie, Simulation, Strategy]
148                     [Adventure, Indie, RPG, Strategy]
149                                                 [RPG]
150                             [RPG, Simulation, Sports]
151                                         [Action, RPG]
152                            [Action, Adventure, Indie]
153                                              [Action]
154                                                 [RPG]
155                                       [Action, Indie]
156         [Action, Adventure, Indie, RPG, Early Access]
157                            [Action, Adventure, Indie]
158                                   [Action, Adventure]
159                                   [Action, Adventure]
160         [Adventure, Indie, RPG, Simulation, Strategy]
161          [Action, Adventure, Casual, RPG, Simulation]
162                                   [Action, Adventure]
163                             [Action, Indie, Strategy]
164     [Adventure, Massively Multiplayer, RPG, Free T...
165                       [Action, Adventure, Indie, RPG]
166     [Action, Adventure, Massively Multiplayer, RPG...
167        [Casual, Indie, RPG, Simulation, Early Access]
168                                         [Action, RPG]
169     [Action, Indie, RPG, Simulation, Strategy, Ear...
170                                   [Action, Adventure]
171                                   [Action, Adventure]
172            [Casual, Indie, RPG, Simulation, Strategy]
173                  [Simulation, Strategy, Free To Play]
174                                   [Action, Adventure]
175              [Action, Adventure, Indie, Early Access]
176                             [Action, Indie, Strategy]
177              [Action, Adventure, Indie, Early Access]
178                                   [Action, Adventure]
179                              [Action, Adventure, RPG]
180                                           [Adventure]
181     [Action, Adventure, Indie, RPG, Simulation, St...
182                                              [Action]
183                                [Simulation, Strategy]
184                                         [Action, RPG]
185          [Action, Adventure, Casual, Indie, Strategy]
186      [Action, Adventure, Casual, Indie, Early Access]
187     [Action, Adventure, Massively Multiplayer, RPG...
188                                              [Action]
189                                                 [RPG]
190                   [Adventure, Indie, RPG, Simulation]
191                                              [Casual]
192                                   [Action, Adventure]
193                                              [Action]
194     [Action, Adventure, Casual, Indie, Simulation,...
195                                              [Action]
196                                   [Action, Adventure]
197     [Casual, Indie, Animation & Modeling, Design &...
198     [Massively Multiplayer, Simulation, Sports, Fr...
199            [Action, Indie, RPG, Simulation, Strategy]
200                                              [Action]
201                    [Casual, Simulation, Free To Play]
202                              [Action, Adventure, RPG]
203                                       [RPG, Strategy]
204                                              [Action]
205                                   [Action, Adventure]
206                                    [Adventure, Indie]
207                  [Action, Adventure, Indie, Strategy]
208                [Action, Adventure, RPG, Free To Play]
209                                              [Action]
210                         [Indie, Simulation, Strategy]
211                       [Adventure, Simulation, Sports]
212                [Action, Adventure, RPG, Early Access]
213                   [Indie, Racing, Simulation, Sports]
214                         [Action, Indie, Free To Play]
215                                         [Action, RPG]
216                                   [Action, Adventure]
217                                [Simulation, Strategy]
218                                            [Strategy]
219                           [Casual, Indie, Simulation]
220     [Action, Adventure, Casual, Indie, Racing, Sim...
221                                   [Action, Adventure]
222                              [Action, Adventure, RPG]
223         [Adventure, Casual, Simulation, Early Access]
224                            [Action, Adventure, Indie]
225                                [Simulation, Strategy]
226                           [Casual, Indie, Simulation]
227                                            [Strategy]
228                               [Action, RPG, Strategy]
229                                   [Action, Adventure]
230                           [Casual, Indie, Simulation]
231                                          [Simulation]
232     [Action, Adventure, Casual, Indie, Simulation,...
233     [Action, Adventure, Casual, Massively Multipla...
234                                           [Adventure]
235                              [Action, Adventure, RPG]
236                                   [Action, Adventure]
237     [Action, Adventure, Massively Multiplayer, Fre...
238                                  [Simulation, Sports]
239                                              [Action]
240                                              [Action]
241                                              [Action]
242                  [Adventure, Casual, Indie, Strategy]
243                                  [Action, Simulation]
244                         [Action, Indie, Early Access]
245                              [Action, Adventure, RPG]
246                        [Action, Simulation, Strategy]
247                                   [Indie, Simulation]
248     [Adventure, Casual, Massively Multiplayer, RPG...
249                    [Action, Adventure, Casual, Indie]
250                                [Simulation, Strategy]
251                                         [Action, RPG]
252                                       [Action, Indie]
253         [Action, Adventure, Indie, RPG, Early Access]
254                                          [Indie, RPG]
255                                   [Indie, Simulation]
256                           [Casual, Indie, Simulation]
257               [Action, RPG, Simulation, Early Access]
258                        [Casual, Simulation, Strategy]
259                                              [Action]
260                                  [Action, Indie, RPG]
261     [Action, Adventure, Indie, Simulation, Early A...
262     [Action, Adventure, Casual, Indie, Simulation,...
263     [Action, Massively Multiplayer, RPG, Free To P...
264                 [Casual, Indie, Simulation, Strategy]
265                 [Casual, Indie, Simulation, Strategy]
266                             [Casual, Indie, Strategy]
267                                [Simulation, Strategy]
268                     [Indie, Simulation, Early Access]
269                       [Action, Adventure, Indie, RPG]
270                              [Action, Adventure, RPG]
271      [Action, Indie, Massively Multiplayer, Strategy]
272                         [Indie, Simulation, Strategy]
273                            [Action, Adventure, Indie]
274     [Action, Adventure, Indie, Massively Multiplay...
275             [Action, Adventure, Indie, RPG, Strategy]
276                                                 [RPG]
277             [Action, RPG, Free To Play, Early Access]
278         [Action, Casual, Indie, Simulation, Strategy]
279                              [Action, Adventure, RPG]
280                                       [Action, Indie]
281                           [Action, RPG, Early Access]
282                        [Casual, Simulation, Strategy]
283                            [Action, Adventure, Indie]
284                           [Casual, Indie, Simulation]
285                       [Action, Adventure, Indie, RPG]
286                                   [Action, Adventure]
287                       [Action, Adventure, Indie, RPG]
288                                            [Strategy]
289                                              [Action]
290                     [Indie, Simulation, Early Access]
291                                         [Action, RPG]
292                    [Casual, Simulation, Early Access]
293                                [Action, Early Access]
294                                              [Action]
295                        [Adventure, Indie, Simulation]
296                                          [Simulation]
297                      [Casual, Strategy, Free To Play]
298                                    [Adventure, Indie]
299                            [Adventure, Casual, Indie]
300                            [Action, Adventure, Indie]
301                          [Action, Casual, Indie, RPG]
302             [Indie, Racing, Simulation, Early Access]
303                                   [Indie, Simulation]
304                                   [Action, Adventure]
305     [Adventure, Free To Play, Massively Multiplaye...
306                                          [Simulation]
307                [Action, Adventure, Indie, Simulation]
308      [Action, Adventure, RPG, Strategy, Early Access]
309                [Adventure, Casual, Indie, Simulation]
310                    [Casual, Simulation, Early Access]
311                                              [Action]
312                           [Action, Indie, Simulation]
313                                  [Action, Simulation]
314                                          [Simulation]
315     [Massively Multiplayer, Racing, Simulation, Sp...
316                                          [Simulation]
317                   [Action, Casual, Indie, Simulation]
318                            [Simulation, Early Access]
319                               [Massively Multiplayer]
320                                       [Action, Indie]
321                                   [Action, Adventure]
322             [Action, Adventure, Indie, RPG, Strategy]
323                               [Action, Casual, Indie]
324                     [Indie, Simulation, Free To Play]
325                     [Action, Casual, Indie, Strategy]
326                [Action, Adventure, Indie, Simulation]
327                [Adventure, Casual, Indie, Simulation]
328     [Action, Adventure, Casual, Indie, Simulation,...
329                [Adventure, Casual, Indie, Simulation]
330            [Action, Indie, RPG, Simulation, Strategy]
331         [Adventure, Indie, RPG, Simulation, Strategy]
332                                              [Action]
333                                       [Action, Indie]
334     [Adventure, Casual, Indie, RPG, Simulation, Ea...
335                                   [Action, Adventure]
336                       [Indie, Strategy, Free To Play]
337                                         [Action, RPG]
338                                       [RPG, Strategy]
339                                           [Adventure]
340                                              [Action]
341                                            [Strategy]
342                                     [Indie, Strategy]
343                                         [Action, RPG]

In [1467]:
dfs_combined['type'].value_counts()

type
game    1285
Name: count, dtype: int64

In [1468]:
dfs_combined[['snapshotDate', 'snapshotID']].drop_duplicates().sort_values('snapshotDate')

    snapshotDate  snapshotID
0     2026-05-17           1
446   2026-06-02           2
811   2026-07-02           3

In [1469]:
df_07_02.head()

,rank,appID,title,url,releaseDate,priceText,finalPriceCents,discountPercent,reviewSummary,reviewPercent,...,monetizationSignal,competitiveSignal,intelligenceTags,riskFlags,insightSummary,snapshotDate,releasedYet,developerID,publisherID,snapshotID
0,1,2767030,Marvel Rivals,https://store.steampowered.com/app/2767030/Mar...,2024-12-05,Free,0,NaN,Mostly Positive,77.0,...,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['high-demand', 'loved-by-players', 'free-to-p...",[],"Marvel Rivals is a commercially aggressive, op...",2026-07-02,True,355,266,3
1,2,730,Counter-Strike 2,https://store.steampowered.com/app/730/Counter...,2012-08-21,Free,1499,NaN,Very Positive,86.0,...,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Counter-Strike 2 is a breakout leader, opportu...",2026-07-02,True,599,426,3
2,3,4704690,MECCHA CHAMELEON,https://store.steampowered.com/app/4704690/MEC...,2026-06-09,$5.99,599,0.0,Very Positive,89.0,...,Paid upfront,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"MECCHA CHAMELEON is a breakout leader, opportu...",2026-07-02,True,637,459,3
3,4,252490,Rust,https://store.steampowered.com/app/252490/Rust/,2018-02-08,$19.99,1999,50.0,Very Positive,86.0,...,Base game plus in-app purchases,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Rust is a breakout leader, opportunity score 9...",2026-07-02,True,179,134,3
4,5,381210,Dead by Daylight,https://store.steampowered.com/app/381210/Dead...,2016-06-14,$7.99,799,60.0,Mostly Positive,79.0,...,Discount-driven sales,Strong incumbent - study positioning and reten...,"['tier-1-opportunity', 'high-demand', 'loved-b...",[],"Dead by Daylight is a breakout leader, opportu...",2026-07-02,True,58,48,3

In [1470]:
dfs_combined['releaseDate'].value_counts(dropna=False)

releaseDate
2025-10-23    12
2026-04-30    11
2026-04-16     9
2020-06-18     9
2026-05-14     8
2026-03-05     8
2026-05-28     8
2026-05-01     6
2026-04-28     6
2026-04-14     6
2015-12-01     6
2023-12-07     6
2025-09-25     6
2025-10-21     6
2026-07-09     6
2026-03-31     6
2026-03-12     6
2026-04-23     6
2026-05-25     6
2025-10-27     6
2025-09-04     5
2026-03-19     5
2026-05-05     5
2007-10-10     5
2023-03-08     5
2024-08-27     5
2025-09-16     5
2025-06-17     5
2026-06-02     5
2013-03-25     4
2025-10-10     4
2025-03-04     4
2025-04-28     4
2025-11-13     4
2025-06-16     4
2026-05-13     4
2025-09-18     4
2016-10-27     4
2026-03-17     4
2025-07-29     4
2024-01-24     4
2026-05-12     4
2015-06-23     4
2025-02-27     4
2025-01-30     4
2023-12-05     4
2025-09-15     4
2024-11-21     4
2024-07-25     4
2022-09-27     4
2024-04-10     4
2026-03-03     4
2025-12-04     4
2026-03-26     4
2026-05-26     4
2020-08-27     4
2026-05-18     3
2012-08-21     3
2024-12-05     3
2026-05-22     3
2020-11-04     3
2018-01-23     3
2026-04-27     3
2023-08-10     3
2016-02-02     3
2015-11-05     3
2018-05-08     3
2019-12-05     3
2013-08-15     3
2016-06-14     3
2018-02-08     3
2025-10-30     3
2024-02-08     3
2023-08-03     3
2025-11-14     3
2022-02-24     3
2024-12-06     3
2025-03-24     3
2016-02-26     3
2025-09-11     3
2023-05-23     3
2014-02-18     3
2017-05-22     3
2025-02-26     3
2024-03-25     3
2023-12-13     3
2017-02-01     3
2020-07-21     3
2016-05-09     3
2020-09-18     3
2026-02-26     3
2025-02-04     3
2020-04-14     3
2026-05-11     3
2017-05-24     3
2023-10-25     3
2017-12-21     3
2024-11-12     3
2018-10-17     3
2023-10-24     3
2020-12-09     3
2019-10-01     3
2025-10-28     3
2015-05-29     3
2022-11-16     3
2022-02-11     3
2026-02-19     3
2020-09-01     3
2023-11-16     3
2025-05-29     3
2015-01-12     3
2024-11-20     3
2020-08-11     3
2025-11-15     3
2016-06-06     3
2024-02-22     3
2020-08-14     3
2023-02-26     3
2013-11-08     3
2024-02-15     3
2014-11-04     3
2018-12-13     3
2022-06-20     3
2024-11-19     3
2020-06-03     3
2022-02-16     3
2025-07-22     3
2017-11-15     3
2021-12-03     3
2012-08-09     3
2024-09-09     3
2013-07-09     3
2024-07-09     3
2018-12-17     3
2022-01-20     3
2024-09-10     3
2023-09-05     3
2024-01-18     3
2024-03-05     3
2016-08-12     3
2022-08-23     3
2011-05-16     3
2025-11-24     3
2015-06-05     3
2022-01-18     3
2025-09-19     3
2022-11-30     3
2013-08-13     3
2025-10-22     3
2022-10-18     3
2017-02-13     3
2015-11-09     3
2021-06-11     3
2022-10-25     3
2024-06-30     3
2025-04-15     3
2023-12-14     3
2015-03-10     3
2019-11-14     3
2023-06-01     3
2026-04-02     3
2023-01-12     3
2019-01-24     3
2025-08-14     3
2025-06-19     3
2025-10-24     3
2025-02-10     3
2025-04-22     3
2024-06-07     3
2019-11-05     3
2024-03-21     3
2025-01-31     3
2017-03-28     3
2026-02-06     3
2021-07-27     3
2026-06-05     3
2025-09-30     3
2018-12-12     3
2020-03-13     3
2024-07-16     3
2026-05-04     3
2022-08-04     3
2021-04-01     3
2019-06-11     3
2025-06-13     3
2024-04-18     3
2026-09-24     3
2024-01-25     3
2025-01-23     3
2026-05-21     3
2025-09-17     3
2026-06-10     3
2024-05-08     2
2015-04-27     2
2026-05-27     2
2026-05-06     2
2024-04-30     2
2020-09-03     2
2025-04-24     2
2019-03-07     2
2024-05-28     2
2025-11-06     2
2025-06-10     2
2022-04-21     2
2026-05-15     2
2026-04-07     2
2026-03-18     2
2018-03-13     2
2023-11-02     2
2019-04-23     2
2025-10-02     2
2026-02-10     2
2026-05-09     2
2023-08-01     2
2023-10-23     2
2013-01-24     2
2026-02-13     2
2024-10-01     2
2018-11-16     2
2018-03-26     2
2017-08-28     2
2019-08-27     2
2026-01-16     2
2023-05-02     2
2026-05-07     2
2022-08-11     2
2017-02-16     2
2021-10-28     2
2025-03-06     2
2026-02-11     2
2024-12-04     2
2024-09-19     2
2012-10-12     2
2018-09-06     2
2019-04-16     2
2021-02-02     2
2026-02-18     2
2024-10-29     2
2026-01-30     2
2023-06-16     2
2016-02-18     2
2024-02-20     2
2021-12-02     2
2024-08-19     2
2021-10-12     2
2017-10-26     2
2010-05-25     2
2024-12-10     2
2024-09-23     2
2024-09-11     2
2023-11-10     2
2021-07-01     2
2018-04-03     2
2025-09-09     2
2019-07-23     2
2023-12-01     2
2026-04-09     2
2021-10-19     2
2018-12-06     2
2024-10-04     2
2017-12-08     2
2016-02-04     2
2010-09-21     2
2024-02-01     2
2025-08-11     2
2015-09-01     2
2025-01-27     2
2024-02-21     2
2017-10-09     2
2018-09-13     2
2017-03-29     2
2023-07-14     2
2022-05-31     2
2023-01-27     2
2016-02-29     2
2023-12-08     2
2020-02-06     2
2018-10-18     2
2020-10-05     2
2025-04-01     2
2026-10-01     2
2026-08-13     2
2023-02-10     2
2026-09-17     2
2022-07-19     2
2025-03-19     2
2026-08-06     2
2021-05-26     2
2024-11-06     2
2016-02-25     2
2023-06-29     2
2012-06-06     2
2015-03-12     2
2017-10-16     2
2023-04-27     2
2026-04-29     2
2025-07-15     2
2024-04-23     2
2020-09-17     2
2017-03-24     2
2017-01-23     2
2016-02-09     2
2024-11-14     2
2025-04-17     2
2023-01-23     2
2025-11-04     2
2024-10-10     2
2022-12-09     2
2021-09-22     2
2018-09-20     2
2024-06-25     2
2023-11-20     2
2026-06-09     2
2025-06-04     2
2025-09-24     2
2025-06-25     2
2024-10-08     2
2023-01-26     2
2024-09-26     2
2026-06-23     2
2017-08-01     2
2021-05-13     1
2026-06-18     1
2026-05-08     1
2023-09-19     1
2026-02-12     1
2023-02-23     1
2023-10-15     1
2014-06-26     1
2021-04-28     1
2020-05-13     1
2015-04-03     1
2026-02-03     1
2019-09-23     1
2026-04-21     1
2017-03-06     1
2019-12-03     1
2020-06-11     1
2011-11-08     1
2025-03-07     1
2024-01-31     1
2016-11-03     1
2014-12-19     1
2017-10-17     1
2025-03-12     1
2025-03-27     1
2024-04-01     1
2006-11-29     1
2021-09-21     1
2015-04-13     1
2009-11-16     1
2024-08-14     1
2014-12-22     1
2020-09-23     1
2017-08-27     1
2023-04-18     1
2025-06-20     1
2026-04-20     1
2026-03-30     1
2014-05-26     1
2025-12-02     1
2021-12-09     1
2025-05-27     1
2022-11-04     1
2023-06-23     1
2026-02-04     1
2018-05-17     1
2009-09-15     1
2015-09-17     1
2026-04-08     1
2025-08-15     1
2021-11-21     1
2024-08-29     1
2021-09-02     1
2025-11-18     1
2025-10-15     1
2020-07-28     1
2008-10-21     1
2023-07-19     1
2025-07-24     1
2026-04-10     1
2021-05-14     1
2022-01-06     1
2020-09-24     1
2025-07-17     1
2022-11-14     1
2024-03-19     1
2023-10-03     1
2019-03-27     1
2007-03-22     1
2013-11-19     1
2009-12-15     1
2018-06-29     1
2019-07-30     1
2021-12-16     1
2014-01-09     1
2023-05-08     1
2025-01-15     1
2021-03-23     1
2021-09-29     1
2020-04-05     1
2015-04-01     1
2020-10-15     1
2022-11-08     1
2025-05-01     1
2022-08-16     1
2025-12-08     1
2026-01-10     1
2008-12-19     1
2023-04-12     1
2025-11-08     1
2023-10-09     1
2024-08-15     1
2026-03-10     1
2026-10-06     1
2020-03-23     1
2025-07-10     1
2023-02-02     1
2013-06-24     1
2023-11-03     1
2017-01-31     1
2025-12-11     1
2023-02-20     1
2018-08-06     1
2026-07-02     1
2022-09-20     1
2022-12-17     1
2017-12-12     1
2027-02-12     1
2026-05-20     1
2024-09-05     1
2025-08-26     1
2019-09-09     1
2026-02-02     1
2026-09-23     1
2026-10-13     1
2024-01-09     1
2025-07-06     1
2026-01-19     1
2018-04-24     1
2023-03-13     1
2025-05-06     1
2022-12-07     1
2021-08-23     1
2019-02-05     1
2019-02-25     1
2019-01-23     1
2023-03-30     1
2026-03-06     1
2020-03-05     1
2017-07-26     1
2022-09-05     1
2012-09-17     1
2025-07-01     1
2020-08-07     1
2015-11-30     1
2019-03-13     1
2019-03-29     1
2026-04-24     1
2013-10-11     1
2018-08-15     1
2025-11-27     1
2025-04-07     1
2014-10-08     1
2015-09-15     1
2025-05-13     1
2025-09-10     1
2023-05-09     1
2010-09-09     1
2018-12-28     1
2022-05-17     1
2018-05-31     1
2024-08-02     1
2025-03-20     1
2026-01-29     1
2012-11-27     1
2022-05-16     1
2020-06-30     1
2013-10-24     1
2024-11-01     1
2018-08-10     1
2009-06-16     1
2019-09-05     1
2017-08-03     1
2021-08-10     1
2016-03-28     1
2022-06-28     1
2023-11-14     1
2022-05-18     1
2022-09-29     1
2016-08-02     1
2012-05-31     1
2024-04-08     1
2013-10-23     1
2023-06-06     1
2017-09-14     1
2022-06-16     1
2025-03-13     1
2025-10-16     1
2020-09-21     1
2024-06-28     1
2026-02-05     1
2025-12-03     1
2018-08-07     1
2026-01-05     1
2024-08-22     1
2020-08-17     1
2026-04-01     1
2016-02-22     1
2023-12-25     1
2026-07-23     1
2026-06-22     1
2024-06-13     1
2025-06-11     1
2019-03-21     1
2012-11-12     1
2022-06-17     1
2024-05-16     1
2022-08-12     1
2026-07-28     1
2025-05-14     1
2015-05-18     1
2023-08-24     1
2023-06-28     1
2025-05-23     1
2023-03-28     1
2022-01-14     1
2024-06-17     1
2016-11-28     1
2022-10-20     1
2025-04-03     1
2023-09-18     1
2010-11-09     1
2014-11-17     1
2023-11-06     1
2024-04-22     1
2021-08-11     1
2022-10-27     1
2024-09-20     1
2022-11-18     1
2025-10-29     1
2022-06-09     1
2024-12-08     1
2017-09-29     1
2019-05-29     1
2026-06-16     1
2022-03-24     1
2021-05-17     1
2020-02-14     1
2017-02-24     1
2018-11-30     1
2012-10-08     1
2024-09-17     1
2017-09-28     1
2020-07-23     1
2020-03-24     1
2024-10-07     1
2023-01-19     1
2025-04-10     1
2025-08-12     1
2023-05-11     1
2026-06-29     1
2022-10-19     1
2016-10-20     1
2013-08-02     1
2024-04-26     1
2026-10-22     1
2012-01-31     1
2016-05-24     1
2026-03-16     1
2017-03-17     1
2023-07-25     1
2018-06-14     1
2022-05-25     1
2023-08-22     1
2009-11-11     1
2008-11-18     1
2025-06-14     1
2026-06-11     1
2026-06-25     1
2020-03-11     1
2013-03-21     1
2019-10-07     1
2024-10-02     1
2016-11-09     1
2021-02-24     1
2025-06-24     1
2020-10-14     1
2025-07-03     1
2015-10-01     1
2019-05-23     1
2016-10-18     1
2025-09-23     1
2019-02-15     1
2018-05-16     1
2025-05-20     1
2017-10-05     1
2017-05-04     1
2024-05-09     1
2022-07-15     1
2023-03-10     1
2026-06-17     1
2018-02-01     1
2022-05-26     1
2014-10-22     1
2025-02-20     1
2025-01-16     1
2023-04-13     1
2023-06-21     1
2025-02-05     1
2024-06-19     1
2022-12-06     1
2023-01-01     1
2024-08-08     1
2024-10-31     1
2016-03-04     1
2015-10-27     1
2020-03-25     1
2024-02-14     1
2025-08-27     1
2025-09-14     1
2025-06-18     1
2022-09-28     1
2024-08-01     1
2009-11-12     1
2026-10-14     1
2022-02-23     1
2024-05-21     1
2025-07-31     1
2008-11-17     1
2015-08-24     1
2013-08-08     1
2025-07-23     1
2023-04-06     1
2019-04-09     1
2022-02-01     1
2025-11-20     1
2025-03-05     1
2014-11-03     1
2024-04-04     1
2022-09-01     1
2014-08-25     1
2020-09-08     1
2014-11-11     1
Name: count, dtype: int64

In [1471]:
dfs_combined[dfs_combined['releaseDate'].isnull()]

Empty DataFrame
Columns: [rank, appID, title, url, releaseDate, priceText, finalPriceCents, discountPercent, reviewSummary, reviewPercent, reviewCount, platforms, imageUrl, scrapedAt, currentPlayers, developer, publisher, genres, tags, type, demandScore, qualityScore, commercialScore, momentumScore, opportunityScore, marketPosition, opportunityType, pricingPosition, audienceSignal, monetizationSignal, competitiveSignal, intelligenceTags, riskFlags, insightSummary, snapshotDate, releasedYet, developerID, publisherID, snapshotID]
Index: []

[0 rows x 39 columns]

In [1472]:
for df, _ in df_05_to_07:
    print(df['releaseDate'].value_counts(dropna=False).head(20))

releaseDate
2026-04-30    7
2026-05-14    6
2025-10-23    6
2026-04-28    4
2026-05-01    3
2026-05-05    3
2026-03-05    3
2026-04-16    3
2020-06-18    3
2023-12-07    3
2025-09-25    3
2025-10-21    3
2026-05-12    3
2024-11-21    3
2026-03-31    3
2026-04-23    3
2025-06-17    3
2026-04-14    2
2013-03-25    2
2025-09-04    2
Name: count, dtype: int64
releaseDate
2026-05-28    6
2026-05-25    4
2026-06-02    4
2026-04-16    4
2026-05-26    3
2026-03-05    3
2025-10-23    3
2026-04-14    3
2020-06-18    3
2025-10-27    3
2026-03-26    3
2023-03-08    3
2015-12-01    2
2026-10-01    2
2026-05-01    2
2026-09-24    2
2025-09-15    2
2025-10-10    2
2024-08-27    2
2023-12-05    2
Name: count, dtype: int64
releaseDate
2026-07-09    3
2020-06-18    3
2025-10-23    3
2026-04-30    3
2026-06-10    3
2026-03-12    3
2025-10-27    3
2026-06-09    2
2025-06-04    2
2025-04-28    2
2025-03-04    2
2025-01-30    2
2025-09-25    2
2015-12-01    2
2026-05-25    2
2025-09-04    2
2021-06-11    2
2015-06-23    2
2025-02-27    2
2023-12-07    2
Name: count, dtype: int64

In [1473]:
df_07_02.dtypes

rank                                int64
appID                               int64
title                                 str
url                                   str
releaseDate                datetime64[us]
priceText                             str
finalPriceCents                     int64
discountPercent                   float64
reviewSummary                         str
reviewPercent                     float64
reviewCount                       float64
platforms                             str
imageUrl                              str
scrapedAt             datetime64[us, UTC]
currentPlayers                    float64
developer                             str
publisher                             str
genres                             object
tags                                  str
type                                  str
demandScore                         int64
qualityScore                        int64
commercialScore                     int64
momentumScore                       int64
opportunityScore                    int64
marketPosition                        str
opportunityType                       str
pricingPosition                       str
audienceSignal                        str
monetizationSignal                    str
competitiveSignal                     str
intelligenceTags                      str
riskFlags                             str
insightSummary                        str
snapshotDate               datetime64[us]
releasedYet                          bool
developerID                         int64
publisherID                         int64
snapshotID                          int64
dtype: object

In [1474]:
dfs_combined.isnull().sum()

rank                    0
appID                   0
title                   0
url                     0
releaseDate             0
priceText               0
finalPriceCents         0
discountPercent       173
reviewSummary          31
reviewPercent          31
reviewCount            31
platforms               0
imageUrl                0
scrapedAt               0
currentPlayers         32
developer               0
publisher               0
genres                  0
tags                    0
type                    0
demandScore             0
qualityScore            0
commercialScore         0
momentumScore           0
opportunityScore        0
marketPosition          0
opportunityType         0
pricingPosition         0
audienceSignal          0
monetizationSignal      0
competitiveSignal       0
intelligenceTags        0
riskFlags               0
insightSummary          0
snapshotDate            0
releasedYet             0
developerID             0
publisherID             0
snapshotID              0
dtype: int64

In [1475]:
dfs_combined.count()

rank                  1285
appID                 1285
title                 1285
url                   1285
releaseDate           1285
priceText             1285
finalPriceCents       1285
discountPercent       1112
reviewSummary         1254
reviewPercent         1254
reviewCount           1254
platforms             1285
imageUrl              1285
scrapedAt             1285
currentPlayers        1253
developer             1285
publisher             1285
genres                1285
tags                  1285
type                  1285
demandScore           1285
qualityScore          1285
commercialScore       1285
momentumScore         1285
opportunityScore      1285
marketPosition        1285
opportunityType       1285
pricingPosition       1285
audienceSignal        1285
monetizationSignal    1285
competitiveSignal     1285
intelligenceTags      1285
riskFlags             1285
insightSummary        1285
snapshotDate          1285
releasedYet           1285
developerID           1285
publisherID           1285
snapshotID            1285
dtype: int64

In [1476]:
#Checking for all games missing developer or publisher information in the combined dataframe
dfs_combined.loc[dfs_combined['developer'].isnull() | dfs_combined['publisher'].isnull(), 'title']

# Changes and updates made to fix missing developer and publisher information in the combined dataframe above so no result is expected now

Series([], Name: title, dtype: str)

In [1477]:
dfs_combined[dfs_combined['title'].str.contains('Marvel Snap', case=False, na=False)][['appID', 'title']]

        appID        title
1125  1997040  MARVEL SNAP

In [1478]:
dfs_combined.loc[dfs_combined['reviewSummary'].isnull() | dfs_combined['reviewPercent'].isnull() | dfs_combined['reviewCount'].isnull() | dfs_combined['currentPlayers'].isnull(), ['title', 'reviewSummary', 'reviewPercent', 'reviewCount', 'currentPlayers', 'releaseDate', 'releasedYet', 'snapshotDate']]

,title,reviewSummary,reviewPercent,reviewCount,currentPlayers,releaseDate,releasedYet,snapshotDate
1,Forza Horizon 6,Very Positive,86.0,7494.0,NaN,2026-05-18,False,2026-05-17
4,LEGO® Batman™: Legacy of the Dark Knight,NaN,NaN,NaN,NaN,2026-05-22,False,2026-05-17
15,Hell Let Loose: Vietnam,NaN,NaN,NaN,NaN,2026-06-18,False,2026-05-17
50,007 First Light,NaN,NaN,NaN,NaN,2026-05-27,False,2026-05-17
134,Assassin's Creed Black Flag Resynced,NaN,NaN,NaN,NaN,2026-07-09,False,2026-05-17
337,Gothic 1 Remake,NaN,NaN,NaN,NaN,2026-06-05,False,2026-05-17
419,STAR WARS: Galactic Racer™,NaN,NaN,NaN,NaN,2026-10-06,False,2026-05-17
436,Avatar Legends: The Fighting Game,NaN,NaN,NaN,NaN,2026-07-02,False,2026-05-17
454,ACE COMBAT 8: WINGS OF THEVE,NaN,NaN,NaN,NaN,2026-10-01,False,2026-06-02
476,CONTROL Resonant,NaN,NaN,NaN,NaN,2026-09-24,False,2026-06-02
502,Hell Let Loose: Vietnam,NaN,NaN,NaN,NaN,2026-08-13,False,2026-06-02
511,Gothic 1 Remake,NaN,NaN,NaN,NaN,2026-06-05,False,2026-06-02
523,Rayman Legends Retold,NaN,NaN,NaN,NaN,2026-10-01,False,2026-06-02
524,Tomb Raider: Legacy of Atlantis,NaN,NaN,NaN,NaN,2027-02-12,False,2026-06-02
542,Onimusha: Way of the Sword,NaN,NaN,NaN,NaN,2026-09-24,False,2026-06-02
555,Assassin's Creed Black Flag Resynced,NaN,NaN,NaN,NaN,2026-07-09,False,2026-06-02
585,"Warhammer 40,000: Dawn of War IV",NaN,NaN,NaN,NaN,2026-09-17,False,2026-06-02
591,MARVEL Tōkon: Fighting Souls,NaN,NaN,NaN,NaN,2026-08-06,False,2026-06-02
600,SILENT HILL: Townfall,NaN,NaN,NaN,NaN,2026-09-23,False,2026-06-02
603,Planet Zoo 2,NaN,NaN,NaN,NaN,2026-10-13,False,2026-06-02
620,Echoes of Aincrad,NaN,NaN,NaN,NaN,2026-07-09,False,2026-06-02
818,Avatar Legends: The Fighting Game,NaN,NaN,NaN,NaN,2026-07-23,False,2026-07-02
819,Assassin's Creed Black Flag Resynced,NaN,NaN,NaN,NaN,2026-07-09,False,2026-07-02
826,EA SPORTS™ College Football 27,NaN,NaN,NaN,NaN,2026-07-09,False,2026-07-02
829,Echoes of Aincrad,NaN,NaN,NaN,NaN,2026-07-09,False,2026-07-02
887,EA SPORTS™ Madden NFL 27,NaN,NaN,NaN,NaN,2026-08-13,False,2026-07-02
893,Halo: Campaign Evolved,NaN,NaN,NaN,NaN,2026-07-28,False,2026-07-02
963,MARVEL Tōkon: Fighting Souls,NaN,NaN,NaN,NaN,2026-08-06,False,2026-07-02
1052,"Warhammer 40,000: Dawn of War IV",NaN,NaN,NaN,NaN,2026-09-17,False,2026-07-02
1103,Call of Duty®: Modern Warfare® 4,NaN,NaN,NaN,NaN,2026-10-22,False,2026-07-02
1153,CONTROL Resonant,NaN,NaN,NaN,NaN,2026-09-24,False,2026-07-02
1248,Castlevania: Belmont's Curse,NaN,NaN,NaN,NaN,2026-10-14,False,2026-07-02

#With the addition of the releasedYet and snapshotDate columns, we can see that the 32 missing values in reviewSummary, reviewPercent, reviewCount, and currentPlayers are due to games that had not yet been released as of the snapshot date. Therefore, these null values are valid and will be kept in the dataset. With the exception of Forza Horizon 6 due to likely reviews from players of  the beta and the early access, for the ones that preordered the premium eddition of the game, the games had no information due to not being released.

In [1479]:
#Above i noticed that there was a null value in priceText, searching through the priceText column I found the appID and title, with that I looked on steam and realized that this is the launcher for all modern Call of Duty games
#As such I will be dropping this row as it is not a game 
dfs_combined.loc[dfs_combined['priceText'].isnull(), ['appID', 'title', 'priceText', 'releaseDate', 'releasedYet', 'snapshotDate']]

Empty DataFrame
Columns: [appID, title, priceText, releaseDate, releasedYet, snapshotDate]
Index: []

In [1480]:
dfs_combined['priceText']

0       $29.99
1       $69.99
2         Free
3         Free
4       $69.99
5        $7.99
6       $19.99
7         Free
8        $7.49
9       $29.99
10      $29.99
11        Free
12       $9.79
13       $7.49
14      $69.99
15      $35.99
16        Free
17       $4.99
18      $19.99
19      $19.79
20        Free
21      $29.99
22      $24.99
23      $69.99
24      $14.99
25        Free
26      $19.99
27      $29.99
28      $39.99
29      $39.99
30      $39.99
31      $59.99
32      $59.99
33        Free
34      $15.74
35      $59.99
36       $9.99
37      $29.99
38        Free
39      $19.99
40       $7.49
41      $38.49
42      $41.99
43       $8.99
44        Free
45      $19.99
46      $19.99
47        Free
48       $4.95
49       $9.99
50      $69.99
51        Free
52      $49.99
53      $17.99
54       $9.99
55       $8.44
56       $9.09
57        Free
58        Free
59        Free
60      $49.99
61      $13.99
62      $69.99
63      $29.99
64      $14.99
65       $5.99
66      $19.99
67      $39.99
68      $29.99
69      $39.99
70      $22.49
71      $40.00
72      $17.49
73       $9.99
74      $39.99
75      $44.99
76        Free
77      $29.99
78      $34.99
79      $49.99
80      $59.99
81        Free
82        Free
83        Free
84      $44.98
85      $47.99
86      $24.99
87        Free
88        Free
89       $4.49
90      $11.99
91       $5.59
92      $23.99
93      $19.99
94      $27.99
95      $49.99
96      $39.99
97      $39.99
98      $29.99
99      $19.90
100     $19.19
101     $39.99
102      $9.99
103     $39.99
104       Free
105     $41.99
106     $29.99
107     $19.99
108     $29.99
109     $24.99
110     $29.99
111      $8.99
112     $49.99
113     $49.99
114     $11.99
115     $29.99
116     $35.00
117       Free
118     $17.99
119     $19.99
120      $8.74
121     $19.99
122      $1.29
123     $14.99
124      $7.99
125     $49.99
126     $19.99
127     $69.99
128     $39.99
129     $59.99
130     $34.99
131       Free
132     $34.99
133     $49.99
134     $59.99
135     $49.99
136       Free
137     $19.99
138      $7.99
139      $6.99
140      $4.99
141      $4.49
142     $59.99
143       Free
144       Free
145     $13.99
146      $5.99
147     $39.99
148      $8.49
149     $49.99
150     $39.99
151      $2.99
152     $15.99
153      $4.99
154     $48.99
155      $9.99
156     $29.99
157     $39.99
158     $59.99
159     $29.99
160     $29.99
161     $39.99
162     $59.99
163      $9.99
164       Free
165      $9.99
166       Free
167     $13.49
168     $39.99
169     $19.99
170     $69.99
171      $9.99
172     $19.99
173       Free
174     $69.99
175      $9.99
176     $19.99
177     $15.99
178      $4.49
179     $39.99
180     $39.99
181     $44.99
182     $39.99
183     $59.99
184      $4.99
185     $29.99
186      $9.99
187       Free
188     $29.99
189     $19.99
190      $9.89
191      $4.99
192     $39.99
193     $19.99
194     $13.99
195     $39.99
196      $8.99
197      $4.99
198       Free
199     $49.99
200     $29.99
201       Free
202     $39.99
203     $49.99
204     $19.79
205     $19.79
206     $17.99
207     $24.99
208       Free
209     $19.79
210     $23.39
211     $19.99
212     $29.99
213     $19.99
214       Free
215      $4.99
216     $39.99
217     $49.99
218     $39.99
219     $39.99
220     $19.99
221     $49.99
222     $69.99
223     $39.99
224      $7.99
225     $29.99
226     $24.99
227     $34.99
228     $39.99
229     $39.99
230      $9.99
231     $19.99
232      $7.99
233       Free
234     $23.99
235     $29.99
236     $39.99
237       Free
238     $69.99
239      $7.49
240      $3.99
241      $9.99
242     $12.74
243     $21.89
244      $9.99
245     $59.99
246     $13.99
247      $4.99
248       Free
249     $11.69
250     $14.99
251      $8.99
252      $4.99
253     $19.99
254     $24.99
255      $9.99
256     $19.32
257     $19.99
258     $14.99
259     $39.63
260     $29.99
261     $24.99
262       Free
263       Free
264     $14.99
265     $11.99
266     $14.99
267     $69.99
268     $19.99
269     $19.99
270     $59.99
271     $49.99
272     $34.99
273       Free
274     $14.99
275     $48.73
276     $49.99
277       Free
278      $5.39
279      $8.99
280      $5.24
281     $24.99
282     $44.99
283      $7.99
284     $14.99
285      $9.99
286      $4.99
287     $13.99
288     $19.99
289     $39.99
290      $9.74
291     $59.99
292      $9.74
293     $39.99
294     $26.99
295     $16.99
296     $29.99
297       Free
298     $19.99
299      $5.99
300     $24.99
301      $4.99
302     $19.99
303     $24.99
304     $19.99
305       Free
306      $8.99
307     $12.99
308     $19.99
309     $19.99
310      $9.99
311     $29.99
312      $9.99
313     $20.99
314     $19.99
315     $19.99
316     $29.99
317      $9.99
318     $15.99
319      $9.99
320      $6.99
321     $39.99
322     $19.99
323      $7.99
324       Free
325      $9.99
326     $39.99
327     $12.99
328      $7.99
329     $19.99
330     $29.99
331      $9.99
332     $29.99
333     $14.99
334     $17.99
335      $5.24
336       Free
337     $49.99
338     $49.99
339     $59.99
340     $38.68
341     $23.99
342     $13.99
343     $59.99
344     $29.99
345      $9.99
346     $29.99
347      $8.99
348      $4.99
349     $15.99
350     $15.39
351     $29.99
352     $24.99
353     $15.99
354     $24.99
355     $59.99
356     $19.99
357     $29.99
358      $9.99
359     $39.99
360     $14.39
361     $19.99
362       Free
363     $44.99
364     $29.99
365     $15.99
366      $9.99
367     $24.99
368      $8.74
369     $24.99
370     $19.99
371     $23.23
372     $39.99
373     $29.99
374     $25.49
375     $29.99
376       Free
377     $29.99
378     $39.99
379      $4.49
380     $39.99
381     $39.99
382     $34.99
383       Free
384     $49.99
385       Free
386     $11.24
387     $39.99
388     $19.99
389     $14.99
390      $9.99
391     $13.49
392       Free
393      $9.99
394      $6.70
395     $19.99
396      $7.49
397     $49.99
398      $4.99
399     $14.99
400     $19.99
401     $34.99
402     $15.19
403     $13.98
404      $8.99
405     $19.99
406     $29.99
407       Free
408     $69.99
409       Free
410     $19.99
411     $69.99
412     $49.99
413     $16.99
414      $5.99
415     $34.99
416     $14.99
417     $29.99
418     $34.99
419     $59.99
420     $59.99
421     $59.99
422       Free
423      $7.49
424     $29.99
425     $13.73
426      $4.99
427       Free
428      $4.99
429     $24.99
430     $19.99
431     $17.99
432     $29.99
433     $24.99
434     $59.99
435     $24.99
436     $29.99
437     $19.99
438       Free
439     $19.99
440     $19.99
441     $24.99
442     $11.99
443     $17.99
444     $14.99
445     $59.99
446       Free
447     $69.99
448       Free
449     $14.99
450     $69.99
451     $39.99
452       Free
453      $7.99
454     $69.99
455     $27.99
456     $29.99
457       Free
458     $69.99
459       Free
460      $7.99
461      $7.99
462     $19.99
463     $24.99
464     $19.99
465       Free
466     $17.99
467     $39.99
468      $6.99
469     $19.79
470       Free
471       Free
472     $24.99
473       Free
474     $27.99
475     $69.99
476     $59.99
477     $19.99
478       Free
479       Free
480     $69.99
481     $27.99
482       Free
483     $14.99
484      $5.99
485       Free
486     $39.99
487     $23.99
488     $27.99
489     $39.99
490     $59.99
491      $9.99
492     $59.99
493      $9.99
494     $49.99
495     $39.99
496     $23.99
497      $5.99
498       Free
499       Free
500      $8.24
501       Free
502     $35.99
503     $19.99
504     $29.99
505      $4.99
506     $49.99
507     $25.48
508       Free
509     $44.99
510       Free
511     $49.99
512       Free
513     $29.99
514      $4.99
515      $9.99
516     $19.99
517      $4.97
518     $69.99
519       Free
520      $9.99
521     $24.99
522     $69.99
523     $39.99
524     $59.99
525     $19.99
526     $40.00
527     $19.99
528      $7.99
529      $4.95
530     $39.99
531     $23.99
532     $34.99
533     $29.99
534       Free
535     $59.99
536     $39.99
537     $49.99
538     $13.99
539     $13.49
540      $6.74
541      $8.99
542     $69.99
543      $7.49
544      $9.99
545      $7.99
546     $22.49
547       Free
548     $19.99
549     $69.99
550     $39.99
551     $14.99
552     $59.99
553     $24.99
554     $22.49
555     $59.99
556     $29.99
557       Free
558      $5.39
559     $69.99
560       Free
561     $39.99
562       Free
563       Free
564     $59.99
565     $39.99
566     $19.99
567     $17.49
568     $39.99
569     $29.99
570      $7.49
571     $26.99
572     $59.99
573     $12.59
574       Free
575     $13.49
576      $4.49
577     $14.99
578       Free
579     $19.99
580     $69.99
581       Free
582     $14.99
583     $35.00
584     $12.49
585     $53.99
586     $14.99
587     $34.99
588     $19.99
589     $19.99
590     $49.99
591     $59.99
592       Free
593       Free
594     $45.00
595     $49.99
596     $29.99
597     $29.99
598     $49.99
599     $19.99
600     $49.99
601       Free
602       Free
603     $49.99
604     $34.99
605     $22.49
606       Free
607     $19.99
608     $29.99
609     $39.99
610     $44.99
611      $4.99
612     $39.99
613       Free
614     $22.49
615     $29.99
616     $14.99
617     $34.99
618      $8.49
619       Free
620     $69.99
621       Free
622      $3.99
623     $29.99
624     $59.99
625     $59.99
626      $9.99
627     $69.99
628      $7.99
629      $2.99
630     $21.24
631     $19.90
632     $19.99
633     $29.99
634     $49.99
635      $4.99
636     $24.99
637     $34.99
638     $14.99
639     $12.24
640     $29.99
641      $5.99
642     $29.99
643       Free
644     $19.99
645     $29.99
646     $24.99
647     $24.99
648     $24.99
649      $8.99
650     $29.99
651      $8.99
652     $13.49
653      $7.99
654     $49.99
655     $69.99
656     $19.99
657       Free
658     $12.99
659     $23.99
660     $15.99
661     $24.99
662       Free
663     $34.99
664     $49.99
665     $19.99
666     $13.99
667     $12.59
668      $2.99
669       Free
670     $59.99
671     $29.99
672       Free
673      $5.99
674      $2.99
675     $10.49
676     $11.99
677      $8.99
678      $4.99
679     $29.99
680     $14.99
681      $7.49
682     $17.99
683     $19.99
684     $29.99
685     $29.99
686     $39.99
687     $24.99
688     $39.99
689     $12.99
690      $2.49
691      $2.99
692      $9.99
693     $20.99
694     $24.99
695     $14.39
696       Free
697     $29.99
698      $6.99
699     $24.99
700      $8.99
701      $4.79
702     $17.49
703     $59.99
704     $19.99
705     $29.99
706     $22.49
707     $13.58
708     $59.99
709     $24.49
710     $14.99
711     $11.99
712      $8.39
713       Free
714     $35.99
715     $59.99
716     $17.99
717     $52.49
718      $9.99
719      $4.49
720     $19.99
721      $3.99
722     $10.39
723     $29.99
724     $17.99
725     $29.99
726     $59.99
727       Free
728     $19.99
729     $29.99
730     $59.99
731     $12.49
732     $39.99
733     $29.99
734       Free
735     $11.99
736      $9.99
737     $39.99
738     $19.99
739     $69.99
740      $6.24
741      $4.99
742     $14.99
743      $7.99
744     $13.49
745       Free
746      $2.49
747     $29.99
748     $79.99
749     $59.99
750     $29.99
751       Free
752     $39.99
753     $29.99
754      $9.99
755      $7.99
756      $2.49
757     $39.99
758      $7.49
759     $15.99
760     $21.99
761     $59.99
762     $19.38
763      $5.99
764      $6.59
765       Free
766      $7.49
767     $29.99
768     $64.98
769     $29.99
770     $44.99
771     $29.99
772     $20.99
773       Free
774     $49.99
775     $29.99
776     $39.99
777      $9.74
778     $25.99
779       Free
780     $39.99
781     $24.99
782     $34.99
783     $19.99
784     $19.99
785     $69.99
786     $14.99
787     $12.99
788     $11.99
789      $5.39
790     $20.99
791     $29.99
792     $19.99
793     $11.99
794     $13.42
795     $24.99
796     $23.99
797     $11.99
798     $19.99
799      $9.99
800     $59.99
801      $7.49
802       Free
803     $12.99
804     $39.99
805     $19.99
806     $39.99
807     $49.99
808     $59.99
809       Free
810      $9.99
811       Free
812       Free
813      $5.99
814     $19.99
815      $7.99
816       Free
817     $17.99
818     $29.99
819     $59.99
820     $19.74
821       Free
822       Free
823       Free
824     $44.99
825      $9.99
826     $69.99
827     $34.83
828     $19.99
829     $69.99
830       Free
831      $1.49
832     $14.99
833     $24.99
834     $14.99
835       Free
836     $29.99
837     $69.99
838       Free
839     $40.19
840     $13.99
841     $19.99
842       Free
843     $31.99
844     $17.99
845     $29.99
846      $9.79
847     $29.99
848     $19.99
849     $40.19
850     $19.79
851     $23.99
852       Free
853     $20.99
854      $1.99
855     $37.49
856     $34.99
857       Free
858     $11.24
859     $59.99
860     $20.99
861     $11.99
862     $40.19
863     $14.99
864     $27.99
865     $29.99
866       Free
867     $13.19
868     $29.39
869     $20.99
870     $39.99
871       Free
872      $8.24
873     $19.99
874      $8.99
875     $13.99
876      $4.95
877      $8.99
878     $55.99
879     $29.99
880     $35.99
881      $4.99
882     $19.99
883      $4.99
884     $24.74
885       Free
886     $14.99
887     $69.99
888       Free
889     $34.99
890     $23.99
891     $69.99
892      $5.99
893     $49.99
894     $23.99
895      $0.99
896      $9.99
897     $29.99
898       Free
899     $23.09
900     $34.99
901      $7.99
902      $2.99
903      $3.99
904      $5.09
905     $24.99
906     $26.99
907      $9.99
908     $29.99
909      $9.99
910     $40.19
911       Free
912      $8.99
913      $9.99
914     $19.99
915     $27.99
916     $69.99
917       Free
918      $2.24
919      $1.99
920     $34.99
921     $12.49
922     $19.99
923     $20.99
924     $22.49
925     $26.99
926     $29.99
927     $23.99
928     $23.99
929      $1.99
930     $29.99
931     $19.99
932     $19.99
933     $32.49
934     $17.99
935       Free
936      $9.99
937     $39.59
938      $2.49
939     $13.39
940     $29.99
941     $13.99
942      $2.49
943       Free
944      $1.49
945     $27.99
946       Free
947     $55.99
948     $23.99
949     $52.49
950     $26.79
951     $11.99
952     $27.99
953      $4.95
954     $27.99
955     $11.99
956      $7.49
957     $29.99
958     $39.89
959     $19.99
960     $17.99
961      $6.49
962      $5.59
963     $59.99
964     $39.99
965     $22.49
966       Free
967     $17.99
968     $22.49
969     $29.99
970       Free
971       Free
972     $27.99
973     $22.03
974     $29.99
975     $27.99
976     $25.48
977     $69.99
978     $13.39
979     $24.99
980      $7.99
981     $13.99
982     $39.99
983     $19.99
984       Free
985     $14.99
986     $27.99
987     $24.99
988     $19.99
989      $9.99
990     $29.99
991     $22.74
992     $20.09
993     $34.99
994       Free
995       Free
996     $15.92
997     $24.99
998      $2.99
999      $9.99
1000     $2.99
1001     $4.99
1002    $31.49
1003    $29.99
1004     $7.49
1005    $34.99
1006    $14.99
1007     $9.00
1008    $17.49
1009      Free
1010    $19.99
1011    $23.99
1012     $6.99
1013    $22.49
1014    $23.99
1015    $19.99
1016    $13.39
1017    $41.99
1018     $4.99
1019    $19.99
1020     $8.99
1021    $34.99
1022     $2.99
1023     $5.99
1024    $41.99
1025    $13.99
1026      Free
1027     $3.99
1028    $13.99
1029     $6.89
1030    $35.00
1031    $15.99
1032      Free
1033     $4.99
1034     $3.99
1035    $22.49
1036     $5.99
1037    $15.99
1038     $9.99
1039     $2.99
1040      Free
1041     $7.49
1042     $8.99
1043     $9.99
1044    $27.99
1045      Free
1046     $9.99
1047     $1.99
1048    $13.99
1049    $19.99
1050    $19.99
1051     $7.49
1052    $53.99
1053     $5.59
1054    $12.24
1055     $3.99
1056    $14.99
1057    $19.99
1058     $1.99
1059     $5.99
1060    $34.99
1061    $29.99
1062      Free
1063    $29.99
1064     $2.79
1065      Free
1066    $14.99
1067     $2.49
1068    $49.99
1069    $19.79
1070    $11.99
1071     $6.24
1072    $15.99
1073    $17.99
1074     $8.74
1075    $13.39
1076    $55.99
1077      Free
1078     $4.49
1079    $29.99
1080    $31.99
1081    $14.99
1082    $14.99
1083     $4.49
1084     $8.99
1085    $16.49
1086    $14.99
1087    $34.99
1088      Free
1089    $22.99
1090    $11.99
1091    $39.99
1092    $15.99
1093     $5.99
1094     $7.99
1095      Free
1096    $11.99
1097    $11.99
1098    $19.79
1099     $7.99
1100     $5.99
1101    $24.99
1102    $25.99
1103    $69.99
1104    $17.99
1105      Free
1106      Free
1107      Free
1108    $59.99
1109    $35.98
1110    $14.99
1111     $9.59
1112    $14.99
1113      Free
1114      Free
1115    $15.99
1116     $8.99
1117    $12.49
1118     $2.99
1119    $15.74
1120    $23.99
1121    $59.99
1122    $19.99
1123     $9.99
1124    $27.99
1125      Free
1126    $17.49
1127    $14.99
1128     $4.49
1129    $14.99
1130    $24.99
1131    $22.49
1132    $14.99
1133      Free
1134    $29.99
1135    $12.49
1136     $4.99
1137    $12.74
1138    $17.49
1139     $5.39
1140     $9.99
1141    $15.99
1142    $34.63
1143    $13.99
1144    $23.99
1145     $8.99
1146     $4.99
1147     $8.99
1148    $12.99
1149    $27.99
1150     $6.39
1151      Free
1152      Free
1153    $59.99
1154    $11.99
1155     $4.99
1156     $4.19
1157    $34.99
1158     $8.99
1159      Free
1160      Free
1161    $11.99
1162      Free
1163    $23.99
1164     $7.99
1165    $29.99
1166      Free
1167    $19.49
1168      Free
1169    $29.99
1170    $19.99
1171     $9.99
1172    $12.49
1173     $8.99
1174     $2.24
1175    $38.99
1176    $11.99
1177      Free
1178     $9.99
1179    $18.19
1180     $7.99
1181      Free
1182     $3.99
1183    $23.99
1184    $14.99
1185    $14.99
1186     $5.99
1187     $6.79
1188     $4.49
1189    $27.99
1190     $7.99
1191    $19.99
1192    $17.49
1193    $10.00
1194     $6.39
1195    $11.24
1196     $7.49
1197      Free
1198    $14.99
1199    $13.49
1200    $15.75
1201     $4.99
1202    $10.04
1203    $12.49
1204     $5.99
1205    $13.99
1206      Free
1207    $14.99
1208    $48.99
1209    $12.05
1210      Free
1211     $7.49
1212     $8.98
1213    $11.99
1214     $7.99
1215    $69.99
1216     $1.99
1217     $3.99
1218    $23.99
1219     $7.79
1220    $19.99
1221     $8.99
1222    $23.99
1223    $19.99
1224     $6.79
1225    $17.99
1226    $11.99
1227    $19.99
1228     $5.24
1229    $29.99
1230      Free
1231    $24.99
1232     $3.99
1233      Free
1234    $11.99
1235    $12.99
1236     $9.09
1237    $11.99
1238     $5.99
1239    $19.79
1240    $39.99
1241    $14.99
1242    $29.99
1243     $9.09
1244     $5.99
1245    $19.49
1246      Free
1247     $4.99
1248    $29.99
1249    $10.79
1250      Free
1251    $29.99
1252     $1.99
1253      Free
1254    $22.49
1255    $11.99
1256    $20.09
1257    $11.99
1258    $11.99
1259    $17.99
1260    $20.99
1261     $2.99
1262     $4.99
1263    $34.99
1264    $15.99
1265     $9.89
1266     $7.99
1267    $11.99
1268     $5.99
1269      Free
1270     $4.99
1271    $19.79
1272    $26.39
1273     $1.49
1274    $39.99
1275     $9.99
1276     $5.99
1277     $7.49
1278     $0.99
1279     $9.99
1280      Free
1281     $4.99
1282     $6.99
1283    $13.59
1284     $7.99
Name: priceText, dtype: str

In [1481]:
#It appears that all values that have nulls in the discountPercent column are for games that are free to play, as such I will be keeping the NaN as no discount would apply to a free to play game
dfs_combined.loc[dfs_combined['discountPercent'].isnull(), ['appID', 'title', 'priceText', 'releaseDate', 'releasedYet', 'snapshotDate', 'discountPercent']]

,appID,title,priceText,releaseDate,releasedYet,snapshotDate,discountPercent
2,730,Counter-Strike 2,Free,2012-08-21,True,2026-05-17,NaN
3,2767030,Marvel Rivals,Free,2024-12-05,True,2026-05-17,NaN
7,1172470,Apex Legends™,Free,2020-11-04,True,2026-05-17,NaN
11,230410,Warframe,Free,2013-03-25,True,2026-05-17,NaN
16,2357570,Overwatch®,Free,2023-08-10,True,2026-05-17,NaN
20,359550,Tom Clancy's Rainbow Six Siege,Free,2015-12-01,True,2026-05-17,NaN
25,236390,War Thunder,Free,2013-08-15,True,2026-05-17,NaN
33,3564740,Where Winds Meet,Free,2025-11-14,True,2026-05-17,NaN
38,3513350,Wuthering Waves,Free,2025-04-28,True,2026-05-17,NaN
44,2141910,Magic: The Gathering Arena,Free,2023-05-23,True,2026-05-17,NaN
47,1222670,The Sims™ 4,Free,2020-06-18,True,2026-05-17,NaN
51,2707930,Palia,Free,2024-03-25,True,2026-05-17,NaN
57,438100,VRChat,Free,2017-02-01,True,2026-05-17,NaN
58,2073850,THE FINALS,Free,2023-12-07,True,2026-05-17,NaN
59,1286830,STAR WARS™: The Old Republic™,Free,2020-07-21,True,2026-05-17,NaN
76,578080,PUBG: BATTLEGROUNDS,Free,2017-12-21,True,2026-05-17,NaN
81,1085660,Destiny 2,Free,2019-10-01,True,2026-05-17,NaN
82,440,Team Fortress 2,Free,2007-10-10,True,2026-05-17,NaN
83,3028330,Battlefield™ REDSEC,Free,2025-10-28,True,2026-05-17,NaN
87,1962663,Call of Duty®: Warzone™,Free,2022-11-16,True,2026-05-17,NaN
88,1599340,Lost Ark,Free,2022-02-11,True,2026-05-17,NaN
104,1407200,World of Tanks,Free,2021-04-28,True,2026-05-17,NaN
117,1973530,Limbus Company,Free,2023-02-26,True,2026-05-17,NaN
131,552990,World of Warships,Free,2017-11-15,True,2026-05-17,NaN
136,216150,MapleStory,Free,2012-08-09,True,2026-05-17,NaN
143,570,Dota 2,Free,2013-07-09,True,2026-05-17,NaN
144,2139460,Once Human,Free,2024-07-09,True,2026-05-17,NaN
164,1284210,Guild Wars 2®,Free,2022-08-23,True,2026-05-17,NaN
166,2073620,Arena Breakout: Infinite,Free,2025-09-15,True,2026-05-17,NaN
173,1449850,Yu-Gi-Oh! Master Duel,Free,2022-01-18,True,2026-05-17,NaN
187,2429640,Throne and Liberty,Free,2024-10-01,True,2026-05-17,NaN
198,380600,Fishing Planet,Free,2017-08-28,True,2026-05-17,NaN
201,4025700,Heartopia,Free,2026-01-16,True,2026-05-17,NaN
208,2074920,The First Descendant,Free,2024-06-30,True,2026-05-17,NaN
214,291550,Brawlhalla,Free,2017-10-17,True,2026-05-17,NaN
233,2437170,SMITE 2,Free,2024-08-27,True,2026-05-17,NaN
237,2507950,Delta Force,Free,2024-12-04,True,2026-05-17,NaN
248,799960,Wizard101,Free,2018-09-06,True,2026-05-17,NaN
262,714010,Aimlabs,Free,2023-06-16,True,2026-05-17,NaN
263,2948190,World of Sea Battle,Free,2025-10-21,True,2026-05-17,NaN
273,1721470,Poppy Playtime,Free,2021-10-12,True,2026-05-17,NaN
277,2016590,Dark and Darker,Free,2024-06-07,True,2026-05-17,NaN
297,886250,Vegas Infinite by PokerStars,Free,2023-11-10,True,2026-05-17,NaN
305,1573360,Infinity Kingdom,Free,2021-07-01,True,2026-05-17,NaN
324,2415010,A Date with Death,Free,2023-12-07,True,2026-05-17,NaN
336,1049590,Eternal Return,Free,2023-07-19,True,2026-05-17,NaN
362,2051620,Enlisted,Free,2024-07-16,True,2026-05-17,NaN
376,2964090,World of Warships: Legends,Free,2026-05-04,True,2026-05-17,NaN
383,1665460,eFootball™,Free,2021-09-29,True,2026-05-17,NaN
385,835570,Conqueror's Blade,Free,2020-04-05,True,2026-05-17,NaN
392,2763740,Revolution Idle,Free,2025-05-01,True,2026-05-17,NaN
407,1282270,Strinova,Free,2024-11-21,True,2026-05-17,NaN
409,588430,Fallout Shelter,Free,2017-03-29,True,2026-05-17,NaN
422,3354750,skate.,Free,2025-09-16,True,2026-05-17,NaN
427,985810,GrandChase,Free,2021-07-27,True,2026-05-17,NaN
438,1335200,Action Taimanin,Free,2020-10-05,True,2026-05-17,NaN
446,730,Counter-Strike 2,Free,2012-08-21,True,2026-06-02,NaN
448,359550,Tom Clancy's Rainbow Six Siege,Free,2015-12-01,True,2026-06-02,NaN
452,1172470,Apex Legends™,Free,2020-11-04,True,2026-06-02,NaN
457,230410,Warframe,Free,2013-03-25,True,2026-06-02,NaN
459,2767030,Marvel Rivals,Free,2024-12-05,True,2026-06-02,NaN
465,1085660,Destiny 2,Free,2019-10-01,True,2026-06-02,NaN
470,2357570,Overwatch®,Free,2023-08-10,True,2026-06-02,NaN
471,2707930,Palia,Free,2024-03-25,True,2026-06-02,NaN
473,438100,VRChat,Free,2017-02-01,True,2026-06-02,NaN
478,3564740,Where Winds Meet,Free,2025-11-14,True,2026-06-02,NaN
479,236390,War Thunder,Free,2013-08-15,True,2026-06-02,NaN
482,2141910,Magic: The Gathering Arena,Free,2023-05-23,True,2026-06-02,NaN
485,3513350,Wuthering Waves,Free,2025-04-28,True,2026-06-02,NaN
498,2073620,Arena Breakout: Infinite,Free,2025-09-15,True,2026-06-02,NaN
499,440,Team Fortress 2,Free,2007-10-10,True,2026-06-02,NaN
501,3354750,skate.,Free,2025-09-16,True,2026-06-02,NaN
508,1286830,STAR WARS™: The Old Republic™,Free,2020-07-21,True,2026-06-02,NaN
510,216150,MapleStory,Free,2012-08-09,True,2026-06-02,NaN
512,1222670,The Sims™ 4,Free,2020-06-18,True,2026-06-02,NaN
519,2073850,THE FINALS,Free,2023-12-07,True,2026-06-02,NaN
534,2437170,SMITE 2,Free,2024-08-27,True,2026-06-02,NaN
547,552990,World of Warships,Free,2017-11-15,True,2026-06-02,NaN
557,4025700,Heartopia,Free,2026-01-16,True,2026-06-02,NaN
560,1973530,Limbus Company,Free,2023-02-26,True,2026-06-02,NaN
562,2139460,Once Human,Free,2024-07-09,True,2026-06-02,NaN
563,1599340,Lost Ark,Free,2022-02-11,True,2026-06-02,NaN
574,1335200,Action Taimanin,Free,2020-10-05,True,2026-06-02,NaN
578,578080,PUBG: BATTLEGROUNDS,Free,2017-12-21,True,2026-06-02,NaN
581,1962663,Call of Duty®: Warzone™,Free,2022-11-16,True,2026-06-02,NaN
592,3028330,Battlefield™ REDSEC,Free,2025-10-28,True,2026-06-02,NaN
593,4125930,Punishing: Gray Raven,Free,2026-02-02,True,2026-06-02,NaN
601,1449850,Yu-Gi-Oh! Master Duel,Free,2022-01-18,True,2026-06-02,NaN
602,2074920,The First Descendant,Free,2024-06-30,True,2026-06-02,NaN
606,1284210,Guild Wars 2®,Free,2022-08-23,True,2026-06-02,NaN
613,2333480,RAID: Shadow Legends,Free,2024-01-09,True,2026-06-02,NaN
619,3950020,Duet Night Abyss,Free,2026-01-19,True,2026-06-02,NaN
621,570,Dota 2,Free,2013-07-09,True,2026-06-02,NaN
643,212500,The Lord of the Rings Online™,Free,2012-06-06,True,2026-06-02,NaN
657,386180,Crossout,Free,2017-07-26,True,2026-06-02,NaN
662,2072560,DRAGON BALL GEKISHIN SQUADRA,Free,2025-09-09,True,2026-06-02,NaN
669,2452280,Mecha BREAK,Free,2025-07-01,True,2026-06-02,NaN
672,2051620,Enlisted,Free,2024-07-16,True,2026-06-02,NaN
696,1974050,Torchlight: Infinite,Free,2023-05-09,True,2026-06-02,NaN
713,588430,Fallout Shelter,Free,2017-03-29,True,2026-06-02,NaN
727,2100280,World of Tanks: HEAT,Free,2026-05-25,True,2026-06-02,NaN
734,2964090,World of Warships: Legends,Free,2026-05-04,True,2026-06-02,NaN
745,886250,Vegas Infinite by PokerStars,Free,2023-11-10,True,2026-06-02,NaN
751,372000,Tree of Savior (English Ver.),Free,2016-03-28,True,2026-06-02,NaN
765,238960,Path of Exile,Free,2013-10-23,True,2026-06-02,NaN
773,3199170,Blood Strike,Free,2025-03-13,True,2026-06-02,NaN
779,1818450,STALCRAFT: X,Free,2022-12-09,True,2026-06-02,NaN
802,1573360,Infinity Kingdom,Free,2021-07-01,True,2026-06-02,NaN
809,2674290,Kings Call,Free,2023-12-25,True,2026-06-02,NaN
811,2767030,Marvel Rivals,Free,2024-12-05,True,2026-07-02,NaN
812,730,Counter-Strike 2,Free,2012-08-21,True,2026-07-02,NaN
816,1172470,Apex Legends™,Free,2020-11-04,True,2026-07-02,NaN
821,1085660,Destiny 2,Free,2019-10-01,True,2026-07-02,NaN
822,230410,Warframe,Free,2013-03-25,True,2026-07-02,NaN
823,2357570,Overwatch®,Free,2023-08-10,True,2026-07-02,NaN
830,3513350,Wuthering Waves,Free,2025-04-28,True,2026-07-02,NaN
835,236390,War Thunder,Free,2013-08-15,True,2026-07-02,NaN
838,2074920,The First Descendant,Free,2024-06-30,True,2026-07-02,NaN
842,359550,Tom Clancy's Rainbow Six Siege,Free,2015-12-01,True,2026-07-02,NaN
852,2141910,Magic: The Gathering Arena,Free,2023-05-23,True,2026-07-02,NaN
857,1222670,The Sims™ 4,Free,2020-06-18,True,2026-07-02,NaN
866,216150,MapleStory,Free,2012-08-09,True,2026-07-02,NaN
871,570,Dota 2,Free,2013-07-09,True,2026-07-02,NaN
885,2073620,Arena Breakout: Infinite,Free,2025-09-15,True,2026-07-02,NaN
888,2139460,Once Human,Free,2024-07-09,True,2026-07-02,NaN
898,3564740,Where Winds Meet,Free,2025-11-14,True,2026-07-02,NaN
911,2429640,Throne and Liberty,Free,2024-10-01,True,2026-07-02,NaN
917,578080,PUBG: BATTLEGROUNDS,Free,2017-12-21,True,2026-07-02,NaN
935,440,Team Fortress 2,Free,2007-10-10,True,2026-07-02,NaN
943,1284210,Guild Wars 2®,Free,2022-08-23,True,2026-07-02,NaN
946,1973530,Limbus Company,Free,2023-02-26,True,2026-07-02,NaN
966,2073850,THE FINALS,Free,2023-12-07,True,2026-07-02,NaN
970,1962663,Call of Duty®: Warzone™,Free,2022-11-16,True,2026-07-02,NaN
971,552990,World of Warships,Free,2017-11-15,True,2026-07-02,NaN
984,1286830,STAR WARS™: The Old Republic™,Free,2020-07-21,True,2026-07-02,NaN
994,438100,VRChat,Free,2017-02-01,True,2026-07-02,NaN
995,1599340,Lost Ark,Free,2022-02-11,True,2026-07-02,NaN
1009,1203220,NARAKA: BLADEPOINT,Free,2021-08-11,True,2026-07-02,NaN
1026,2707930,Palia,Free,2024-03-25,True,2026-07-02,NaN
1032,4162040,Zenless Zone Zero,Free,2026-06-16,True,2026-07-02,NaN
1040,3061570,Persona5: The Phantom X,Free,2025-06-25,True,2026-07-02,NaN
1045,3028330,Battlefield™ REDSEC,Free,2025-10-28,True,2026-07-02,NaN
1062,2437170,SMITE 2,Free,2024-08-27,True,2026-07-02,NaN
1065,1449850,Yu-Gi-Oh! Master Duel,Free,2022-01-18,True,2026-07-02,NaN
1077,2507950,Delta Force,Free,2024-12-04,True,2026-07-02,NaN
1088,3092660,Reverse: 1999,Free,2024-10-08,True,2026-07-02,NaN
1095,223750,DCS World Steam Edition,Free,2013-08-02,True,2026-07-02,NaN
1105,799960,Wizard101,Free,2018-09-06,True,2026-07-02,NaN
1106,380600,Fishing Planet,Free,2017-08-28,True,2026-07-02,NaN
1107,9900,Star Trek Online,Free,2012-01-31,True,2026-07-02,NaN
1113,3679080,The Seven Deadly Sins: Origin,Free,2026-03-16,True,2026-07-02,NaN
1114,714010,Aimlabs,Free,2023-06-16,True,2026-07-02,NaN
1125,1997040,MARVEL SNAP,Free,2023-08-22,True,2026-07-02,NaN
1133,2584990,Shadowverse: Worlds Beyond,Free,2025-06-14,True,2026-07-02,NaN
1151,2051620,Enlisted,Free,2024-07-16,True,2026-07-02,NaN
1152,3164330,Infinity Nikki,Free,2025-04-28,True,2026-07-02,NaN
1159,444200,World of Tanks Blitz,Free,2016-11-09,True,2026-07-02,NaN
1160,1343370,Old School RuneScape,Free,2021-02-24,True,2026-07-02,NaN
1162,3224770,Umamusume: Pretty Derby,Free,2025-06-24,True,2026-07-02,NaN
1166,2325290,Sky: Children of the Light,Free,2024-04-10,True,2026-07-02,NaN
1168,3557620,Blue Archive,Free,2025-07-03,True,2026-07-02,NaN
1177,459820,Crush Crush,Free,2016-10-18,True,2026-07-02,NaN
1181,761890,Albion Online,Free,2018-05-16,True,2026-07-02,NaN
1197,327070,Gloria Victis: Medieval MMORPG,Free,2026-06-17,True,2026-07-02,NaN
1206,2016590,Dark and Darker,Free,2024-06-07,True,2026-07-02,NaN
1210,2328760,Pinball FX,Free,2023-04-13,True,2026-07-02,NaN
1230,1818450,STALZONE,Free,2022-12-09,True,2026-07-02,NaN
1233,627690,Idle Champions of the Forgotten Realms,Free,2020-03-25,True,2026-07-02,NaN
1246,3052450,Morimens,Free,2024-08-01,True,2026-07-02,NaN
1250,2819520,Viking Rise,Free,2024-05-21,True,2026-07-02,NaN
1253,212500,The Lord of the Rings Online™,Free,2012-06-06,True,2026-07-02,NaN
1269,2379740,Wizardry Variants Daphne,Free,2025-03-05,True,2026-07-02,NaN
1280,3354750,skate.,Free,2025-09-16,True,2026-07-02,NaN

In [1482]:
dfs_combined['discountPercent'].isnull().sum()

np.int64(173)

In [1483]:
dfs_combined.dtypes

rank                                int64
appID                               int64
title                                 str
url                                   str
releaseDate                datetime64[us]
priceText                             str
finalPriceCents                     int64
discountPercent                   float64
reviewSummary                         str
reviewPercent                     float64
reviewCount                       float64
platforms                             str
imageUrl                              str
scrapedAt             datetime64[us, UTC]
currentPlayers                    float64
developer                             str
publisher                             str
genres                             object
tags                                  str
type                                  str
demandScore                         int64
qualityScore                        int64
commercialScore                     int64
momentumScore                       int64
opportunityScore                    int64
marketPosition                        str
opportunityType                       str
pricingPosition                       str
audienceSignal                        str
monetizationSignal                    str
competitiveSignal                     str
intelligenceTags                      str
riskFlags                             str
insightSummary                        str
snapshotDate               datetime64[us]
releasedYet                          bool
developerID                         int64
publisherID                         int64
snapshotID                          int64
dtype: object

In [1484]:
dfs_combined['scrapedAt'].isnull().sum()

np.int64(0)